### ISSUE TITLE
[Bug] Xtreme Zone - Configuration failed: Login failed: No form found

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1004]
Full error message when trying to configure Xtreme Zone:
Configuration failed: Login failed: No form found on http://myxz.org/login.php using form selector form

Enhanced log attached. Thanks.
[log.txt](https://github.com/Jackett/Jackett/files/739467/log.txt)

Jackett version:  0.7.952.0
Mono version (if not using Windows): N/A

**Comment by kaso17** [comment]
They changed to https :)
Fixed with 8b6f7095ae1b604af52b80e87e6d5599f6d3f49e + 60a322e15375e1ef6ff72b5a1ad30b72b751f6f9

**Comment by armani316** [comment]
@kaso17 Are you able to configure it after the 0.7.962.0 update? Looks like their certificate has expire, like TranceTraffic's.

**Comment by armani316** [comment]
**Error: An error occurred while sending the request.**
The error I get as soon as I try to add Xtreme Zone as an indexer. It won't even allow me to enter my username & password. Seems like they renewed their security certificate, but the problem still exists.
[log.txt](https://github.com/Jackett/Jackett/files/742444/log.txt)

**Comment by kaso17** [comment]
Now we've to change the Site link to "https://www.myxz.org/"
Default changed with 21d45c29916d7d9400e884a249d1054c530566aa
