### ISSUE TITLE
RARBG RSS Major problem

### ISSUE THREAD

**Issue by Wilson2013** [Jackett/Jackett#11021]
Environment - Win 7 64-Bit QBittorrent v4.3.3

OS - Win 7 64-Bit

.Net Version - 4.8.something

Jackett Version - v0.17.456

Last Working Jackett Version - The one before this one

Are you using a proxy or VPN? - No

Description - RARBG now duplicates entries in the RSS list. eg after 6 hours I'll have 6 of the newest entry, 6 of the second, maybe 5 of the next couple, 5 or 4 of the next few, etc. It just adds the newest entries to the list, whether they're already there or not. All other sites working perfectly.

Logged Error Messages - None

Screenshots

![Capture](https://user-images.githubusercontent.com/46002178/107094077-4e6c3300-67fe-11eb-9a78-21e36f18d180.JPG)

**Comment by ilike2burnthing** [comment]
Disable Jackett's cache, apply server settings, enable the cache, apply server settings; see if the issue continues.

If so, disable it again and see if the issue continues.

If so, I'd lean heavily towards this being yet another issue with RARBG's API, as there haven't been any changes to the indexer since last year.

**Comment by Wilson2013** [comment]
Thanks for the quick reply.

I went through the steps, issue is still there.

**Comment by ilike2burnthing** [comment]
Just so I'm testing this right, you have clicked the `Copy RSS Feed` button for RARBG in Jackett, clicked the `New subscription` button in the `RSS` tab in qbit and pasted the URL for Jackett's RARBG RSS feed, and in qbit's setting you have enabled fetching RSS feeds?

Are you using the default values for 30mins and 50 articles?

If you manually update the feed in qbit, does this replication issue occur, or is it only on auto-refresh?

**Comment by Wilson2013** [comment]
Yes that's how I did it. I have a number of other Jackett RSS feeds for other sites in QBit all still working perfectly.

I'm actually using 16 mins but changed to 30 and same result.

RARBG Replication issue occurs both on auto-refresh and manual update.

**Comment by ilike2burnthing** [comment]
I bumped the article limit for qbit up to 500 and disabled the cache in Jackett, and now every manual refresh results in some (but not all) of the articles being duplicated. Jackett shows 100 releases being fetched each time, and the RSS feed itself shows 100 releases.

While it doesn't seem to be happening for any other Jackett indexer in qbit (I just used a quick sample), the same issue for RARBG is not happening in an RSS reader like QuiteRSS. That suggest that while it is RARBG specific, the issue lies with qbit.

I'll leave this issue open in case I've missed something, but I think you'd need to address this over at https://github.com/qbittorrent/qBittorrent/issues

**Comment by nydave69** [comment]
i'm seeing the same thing with utorrent..
and it just started in the last 3 days..  no changes that i've made and no utorrent updates..
I know jacket has updated.. current Jackett Version v0.17.449.. and it is with RARBG RSS feed only..

**Comment by ilike2burnthing** [comment]
No changes have been made to the indexer since last year, and no significant changes have been made to Jackett in that time either - other than indexer updates and fixes, there has only been a change to the number of decimal places torrent sizes are given in (https://github.com/Jackett/Jackett/commit/4f9b0b0c81c6d55d697a18965513bea03a9c85fe) and the removal of some legacy code to do with logos (https://github.com/Jackett/Jackett/commit/456338399b30b62edccb85d88a97311bfc06a4e3), both of those being on Jan 17th.

If there has been a change to RARBG's API, it doesn't seem to affect normal RSS feed readers, just torrent clients. A complete guess would be something relating to how unique articles are identified.

**Comment by ilike2burnthing** [comment]
Of course 2mins later I would find the likely issue 🙄

RARBG is randomising the ports for their trackers in the magnet links, e.g.:
```
[...]tr=udp%3A%2F%2F9.rarbg.me%3A2990&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2990
```
vs:
```
[...]tr=udp%3A%2F%2F9.rarbg.me%3A2800&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2800
```
as well as plenty of others variations.

This is used for the guid, link, enclosure url, and magneturl, and I'm not sure which of these is being used by the torrent clients.

@ngosang can this be standardised without breaking anything in the future?

**Comment by ngosang** [comment]
> This is used for the guid, link, enclosure url, and magneturl, and I'm not sure which of these is being used by the torrent clients.

RSS clients use the GUID field. The general logic in Jackett is to use the details URL and then the torrent and magnet links. This is fine and it's working in most cases. https://github.com/Jackett/Jackett/blob/6e527823b55adf3edcd2b948b24ce57f02eacfda/src/Jackett.Common/Indexers/BaseIndexer.cs#L288
In RarBG we were using the magnet link. It's fixed now.

**Comment by ilike2burnthing** [comment]
[v0.17.474](https://github.com/Jackett/Jackett/releases/tag/v0.17.474)

**Comment by nydave69** [comment]
I am still seeing this issue after upgrading to Jackett Version v0.17.474..

**Comment by ilike2burnthing** [comment]
Also try removing the feed and re-adding.

**Comment by nydave69** [comment]
Tried all the above...  Still adding downloads that have already been downloaded.

I have started to leave the finished downloads listed so that when they are re-added they don't actually download again. only way I could get it to stop.   It is not as bad as before the last update has cut down on a lot of the re-downloads..  I can't seem to find a common denominator for the one's it does resubmit. 

![image](https://user-images.githubusercontent.com/14140816/107418644-e743cc80-6ae4-11eb-99a5-4d0084ceb06e.png)


I have all the other RSS feeds disabled while I am trying to figure this one out....

**Comment by ilike2burnthing** [comment]
I tried it with uTorrent v3.5.5 yesterday and it was working fine, but that was starting from scratch in a sandbox, not upgrading anything. Are you using an older version of uTorrent (e.g. v2.2.1)?

Try removing the feed and restart uTorrent, then remove the indexer and restart Jackett, then re-add the indexer and the feed, see if that helps.

**Comment by nydave69** [comment]
uTorrent 3.0

Nothing but Jacket has been upgraded...   Jackett Version v0.17.474

I did all that...  Rebooted all system,  deleted Jacket....  Deleted The Feeds ....  Deleted History...,.  
Reinstalled Jacket...  added all the Trackers back in...  setup the RSS feeds again in uTorrent..  seemed good till today...

Was just going to install the feed without Jacket and see how that works..

**Comment by nydave69** [comment]
Installed the rarbg feed directly and it grabbed the latest 2 only, so it looks like its working...

**Comment by nydave69** [comment]
Let it run overnight going directly to RARBG RSS...  no dups were downloaded.

So the issue is still with Jacket

**Comment by ilike2burnthing** [comment]
I can't recreate this issue, any variation of settings I use works fine. Not sure if it's caused by using an older version of uTorrent. Try upgrading? As a test you could try installing qbittorrent and see if the issue continues there.

**Comment by nydave69** [comment]
I really don't want to upgrade uTorrent..
This issue only started a week ago and nothing had changed except the Jacket version.
And my direct RSS feed to RARBG works...

Guess I'll just leave this way..  Funny that all the other Jacket RSS feeds work.. no issue there.

thanks for your help...
