### ISSUE TITLE
No results from FinElite

### ISSUE THREAD

**Issue by ronilaukkarinen** [Jackett/Jackett#13642]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running in Docker: Yes
Jackett Version v0.20.2099
```

### Description

Log:

2022-10-13 15:58:59.0542 Info Manual search in FinElite for shallow => Found 0 releases

NZBHydra2 also returns 0 results.
There should definitely be results.

The website itself works and everything in it.

### Logged Error Messages

```text
2022-10-13 15:58:59.0542 Info Manual search in FinElite for shallow => Found 0 releases
```

### Screenshots

![image](https://user-images.githubusercontent.com/1534150/195647769-372a2a90-e020-4083-9299-3020cf7ea937.png)

**Comment by garfield69** [comment]
None of the current team have an account on the site, so we cannot research independently.
Which means that unless you have an invite then you are going to have to provide more data.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log including the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by ronilaukkarinen** [comment]
Sorry, my bad, somehow missed that step of the process.

Side notes: I have tried relogin, didn't help. Raw RSS feed works from Jackett but still getting 0 results.

I have 0 invites, sorry, otherwise would gladly share.

Here's HTML with user details removed:

[Haku_ 'shallow' - Finelite.txt](https://github.com/Jackett/Jackett/files/9779660/Haku_.shallow.-.Finelite.txt)

Here's full log.txt:

[log.txt](https://github.com/Jackett/Jackett/files/9779676/log.txt)

**Comment by ronilaukkarinen** [comment]
Somehow the enhanced tick didn't stay on. I blame my sleep deprivation from this out of focusedness... forgive me.

Here, with user details removed, the end of it should contain debug logs with test pressed and with same manual search performed:

[log.txt](https://github.com/Jackett/Jackett/files/9779789/log.txt)

**Comment by garfield69** [comment]
OK. the 2nd log was very useful.
what it showed was that the TEST (keywordless search) did a GET to the site and returned 100 results
then the manual search looked up the jackett cache and found no matching hits, so that is why you got 0 results.

If you only use Jackett for manual searches, which is to say, you do not use Sonarr or Radarr or other torznab apps, then you can switch off the Jackett cache so that all the requests that Jackett makes go to the web sites.

So turn off the cache and see if that works.

**Comment by ronilaukkarinen** [comment]
I use Radarr and Sonarr via NZBHydra2/torznab and all of them return 0 results no matter what I search. Word shallow should return Shallow Grave, it does so on the site and it's shown on RSS but cannot be found in Jackett manual search or via torznab or apps. Not even with cache disabled, just re-tested.

**Comment by garfield69** [comment]
please turn on enhanced logging, and search for shallow so I can see what gets returned. thanks.

**Comment by garfield69** [comment]
In case I am not clear, I meant: ensure that cache is turned off, restart Jackett, turn on the enhanced logging and do a manual search. :-)
Thanks.

**Comment by ronilaukkarinen** [comment]
Done.

[log (1).txt](https://github.com/Jackett/Jackett/files/9780519/log.1.txt)

**Comment by garfield69** [comment]
you searched TheScenePlace
this time try FinElite ;-D

**Comment by ronilaukkarinen** [comment]
Humm but I did search FinElite.

Did it again, here's the logfile again:

[log5.txt](https://github.com/Jackett/Jackett/files/9780885/log5.txt)

**Comment by ilike2burnthing** [comment]
That is exactly the same file and is definitely showing results for TheScenePlace.

**Comment by ronilaukkarinen** [comment]
That's weird. I definitely searched FinElite. Got the file on my mobile phone, maybe it cached it or something. Will send another as soon as I get to desktop...

**Comment by ronilaukkarinen** [comment]
How about now? (I've checked out the file and there's definitely finelite mentioned)

[log.txt](https://github.com/Jackett/Jackett/files/9783489/log.txt)

**Comment by garfield69** [comment]
yes, that's is a winner.
and the issue is with the date format, where the month which was once 2 digit can now be a single digit without the leading zero.
which is why the keywordless search currently works as the current month is 10, where as the search for shallow have month 9
should be fixed for the next release of jackett due out in about 22 hours.

**Comment by ronilaukkarinen** [comment]
Awesome, thank you so much @garfield69! Also thanks for tolerating me messing up the files. Have a nice weekend!

**Comment by garfield69** [comment]
v0.20.2109

**Comment by ronilaukkarinen** [comment]
@garfield69 I'm now on Version v0.20.2109 now but still getting 0 results. Cache is disabled.

```
2022-10-15 11:19:24.5576 Info Torznab search in FinElite for shallow => Found 0 releases
```

Enhanced log:

[log-6.txt](https://github.com/Jackett/Jackett/files/9791951/log-6.txt)

**Comment by ilike2burnthing** [comment]
8 results returned for the keyword `shallow`, 2 contain `shallow` in their title, but all skipped as a result of the andmatch filter, which is confusing.

Are all other keyword searches the same - all results skipped due to the andmatch filter?

If this returns those 8 results:
https://finelite.org/selaa.php?search=shallow&hae=1&incldead=1&freeleech=&sort=4&type=desc
does this only return the 2 results with `shallow` in their titles:
https://finelite.org/selaa.php?search=shallow&hae=0&incldead=1&freeleech=&sort=4&type=desc

**Comment by ronilaukkarinen** [comment]
> If this returns those 8 results:
https://finelite.org/selaa.php?search=shallow&hae=1&incldead=1&freeleech=&sort=4&type=desc

Correct.

> does this only return the 2 results with shallow in their titles:
https://finelite.org/selaa.php?search=shallow&hae=0&incldead=1&freeleech=&sort=4&type=desc

Correct.

> Also, can you search by imdbid by using hae=4?

This doesn't work.

**Comment by ilike2burnthing** [comment]
Should be fixed in the next release. Out in ~17hrs.

**Comment by garfield69** [comment]
v0.20.2113

**Comment by ronilaukkarinen** [comment]
Almost there. Manual search returns results but no titles. Nzbhydra2/sonarr/radarr rejects all results.

Nzbhydra2:
![image](https://user-images.githubusercontent.com/1534150/196032661-6ea84972-d5f6-44ec-acd0-b1d2d7224834.png)

Jackett manual search:
![image](https://user-images.githubusercontent.com/1534150/196032672-ebdd3696-1380-4e9b-9f57-e8274bb0f20e.png)

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/9794323/log.txt)

**Comment by ilike2burnthing** [comment]
Fix in 18hrs. As far as I can see, everything else should be fine.

**Comment by garfield69** [comment]
v0.20.2122

**Comment by ronilaukkarinen** [comment]
Yeahh, now it works perfectly! Thanks!
