### ISSUE TITLE
[iptorrents] (updating) Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

### ISSUE THREAD

**Issue by Dialatech2303** [Jackett/Jackett#14606]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: Yes 
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.583-ls121) Via Unraid 
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.38.0 (64bit OS) (64bit process)
Environment version: 6.0.20 (/app/Jackett/)
```

### Description

Configure IPT with the cookie and the User-Agent. It lasts around 24 hours and then it loses its information and gives the following error.

Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

I re-enter the details and it works again. Every day I have to renew the cookie and User-Agent. I also have a friend who has the same setup and the same issue.

### Logged Error Messages

```text
System.Exception: Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
Jackett.Common.IndexerException: Exception (torrents): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
```

### Screenshots

No screenshot

**Comment by ilike2burnthing** [comment]
In this case the cookie expires after 24hrs. We're unable to use credentials login as the login page can present a captcha challenge.

**Comment by Dialatech2303** [comment]
I get this error even when renewing the cookie now. Even even add it or use IPT via jackett anymore.

**Comment by alyssadev** [comment]
I've been having this issue as well. A manual request to iptorrents with the below curl worked, returning a logged in page:

```bash
curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{
  "cmd": "request.get",
  "url":"http://ipt.lol/",
  "maxTimeout": 60000,
  "cookies": [{"name": "uid", "value": "12345"}, {"name": "pass", "value": "abcde"}]
}'
```

It seems Jackett isn't sending any login cookies with its initial request, so it's not getting anything but the login page as a result:

    Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://ipt.lol/t?o=time'}
    Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'http://ipt.lol/', 'maxTimeout': 60000, 'cookies': [{'name': 'uid', 'value': '12345'}, {'name': 'pass', 'value': 'abcde'}]}

Sending the cookies provided by the user with requests to FlareSolverr would mean you'd only need one request to get the data; alternatively (or additionally) setting the `session` value in the request would result in a static browser instance which would likely solve the problem entirely.

**Comment by mariotacke** [comment]
Having the same issue, please reopen.

**Comment by blha303** [comment]
This should have been fixed in #14627, try updating Jackett

**Comment by alyssadev** [comment]
This should have been fixed in #14627, try updating Jackett

**Comment by mariotacke** [comment]
Looks like the main domain has/had an expired certificate and thus was unable to connect. I tried several other endpoints until (the very last one worked). Thanks.

**Comment by alyssadev** [comment]
This is still not working in v0.21.867. It definitely seems to be getting the cookies from flaresolverr at least. I suspected it could be due to the user agent difference between my browser and flaresolverr, so I set the user agent in Jackett to the agent reported in flaresolverr:8191 userAgent, but no improvement.

```
jackett_1       | 09-23 22:45:29 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://ipt.lol/t?o=time)
flaresolverr_1  | 2023-09-23 22:45:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://ipt.lol/t?o=time'}
flaresolverr_1  | 2023-09-23 22:45:32 INFO     Challenge detected. Title found: Just a moment...
flaresolverr_1  | 2023-09-23 22:45:43 INFO     Challenge solved!
flaresolverr_1  | 2023-09-23 22:45:43 INFO     Response in 14.663 s
flaresolverr_1  | 2023-09-23 22:45:43 INFO     192.168.16.3 POST http://flaresolverr:8191/v1 200 OK
jackett_1       | 09-23 22:45:44 Debug cf_clearance=$CF_CLEARANCE
jackett_1       | 09-23 22:45:44 Debug WebClient(HttpWebClient2): Returning Redirect => https://ipt.lol/login.php 0 bytes
jackett_1       | 09-23 22:45:44 Debug updating Cookies uid=$UID; pass=$PASS => uid=$UID; pass=$PASS; cf_clearance=$CF_CLEARANCE
jackett_1       | 09-23 22:45:44 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 15676.2799ms
jackett_1       | 09-23 22:45:44 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
jackett_1       | 09-23 22:45:44 Error System.Exception: Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
```
