### ISSUE TITLE
TorrentLeech Issue

### ISSUE THREAD

**Issue by jlogan** [Jackett/Jackett#3051]
I haven't been able to get TorrentLeech to work ever since they updated the design. Log attached.

[jackett-log.txt](https://github.com/Jackett/Jackett/files/1967038/jackett-log.txt)

**Comment by aarsenca** [comment]
Hi. 

You don't mention which version of Jackett you are running. There have been several Jackett versions since the updated TL design. The main issue was fixed in version 0.8.857.

Regards.

**Comment by jlogan** [comment]
Jackett Version 0.8.857.0

**Comment by aarsenca** [comment]
You might want to try with the current version. Personally, I run the current version with Mono JIT compiler version 5.10.1.20. I have had no problems with the new TL design since version 0.8.857.

**Comment by jlogan** [comment]
I updated to latest. Still not working. Attached latest logs.
[latest-logs.txt](https://github.com/Jackett/Jackett/files/1968652/latest-logs.txt)

**Comment by aarsenca** [comment]
Sorry, I can't help you with the log...

**Comment by jlogan** [comment]
Thanks. I also use Mono. Did you have to do any setting changes from within TL after new design @aarsenca ?

**Comment by aarsenca** [comment]
I'm not at home now to check my settings, but I believe some people had issues because they were pointing to an old version of TL whereas Jackett now expects the new version. See issue 2882. Quoting hamishsw:

```
just for the benefit of others that after updating Jacket I was able to connect back up to TL and Sonarr/Radarr grabs/search/download are working as expected.

However it did not work with http://v4.torrentleech.org/

Instead I used https://www.torrentleech.org/
```

**Comment by flightlevel** [comment]
@jlogan Follow advice from @aarsenca above

If it still doesn't work post a FULL ENHANCED log https://github.com/Jackett/Jackett#troubleshooting

**Comment by jlogan** [comment]
It's working now after the Jackett update.
