### ISSUE TITLE
Timezone is not taken into account when returning results from revolutiontt

### ISSUE THREAD

**Issue by samwiseg00** [Jackett/Jackett#3094]
**Jackett version**:  
0.8.778.0

**Mono version** (if not using Windows):  
5.4.1.7

When results from revolutiontt are returned the timezone is not taken into account which in turn makes the release seem older then they really are. 

Normally this would not be a big deal but sonarr relies on age when doing delay profiles. 

revolutiontt XML:
```xml
<description>
Category: TV/HDx264 Size: 379.05 MB Status: 18 seeders and 21 leechers Added: 2018-05-09 23:12:00 Description: Release.EXTENDED.720p.WEB.x264-TBS 05/10/2018
</description>
<pubDate>Wed, 09 May 2018 23:12:00 -0400</pubDate>
</item>
```

Jackett XML
```xml
   <title>Release.EXTENDED.720p.WEB.x264-TBS</title>
      <guid>(REMOVED)</comments>
      <pubDate>Wed, 09 May 2018 23:12:00 +0200</pubDate>
```

**Comment by flightlevel** [comment]
@samwiseg00 Can you check their website and see if you set your timezone as part of your profile
Also, when you search on their website, are times returned as UTC times or local?

**Comment by samwiseg00** [comment]
I played around with this for a bit. It seems that the timezone setting only changes the display time on the site. It does not change it for the RSS feed.

**Comment by samwiseg00** [comment]
Looking at it again... So what I think is happening is that the time on the RSS is the same as the site setting (I may not have given it enough time to change the times on the RSS feed). In the RSS it says what the time zone that it accounted for... for example 
```
<pubDate>Fri, 11 May 2018 21:24:22 -0400</pubDate>
```
The time is displayed in EDT and the -0400 is the time zone that time stamp is in.

Time displayed on site for the same release.
![2018-05-11_21-30-54](https://user-images.githubusercontent.com/2241731/39952357-9e950188-5562-11e8-8a5d-c439d256c9d7.png)

**Comment by samwiseg00** [comment]
So scratch that.. the server time just so happen to be EDT... So the time stamps that are in the RSS feed are server time and not what is in the profile.

**Comment by kaso17** [comment]
@samwiseg00 the current code actually doesn't use the RSS pudDate field, instead it extracts the time from the added: part of the description.
Can you confirm that this is always UTC-4 too?

**Comment by samwiseg00** [comment]
If you are saying that Jackett scrapes the site then the added time changes with what is set in the profile. Is that the method it uses?

If that was the case wouldn't changing it in the profile result in a change it in the Jackett feed?

I have tried changing my profile to another timezone and I did not see old or new results change time.

sample of the details page. 
![2018-05-13_20-50-20 1](https://user-images.githubusercontent.com/2241731/39973568-5e7a9b88-56ef-11e8-861d-04286778c661.png)

**Comment by kaso17** [comment]
ok, thank you for confirming.
We'll just switch to the pubDate then. Can you please check if the hours and the day have leading zeroes in case of single digit values?

**Comment by samwiseg00** [comment]
yep is it 2 digits
```xml
<description>
Category: TV/SDx264 Size: 598.95 MB Status: 11 seeders and no leecher Added: 2018-05-14 06:27:34 Description: RELEASE.WEB.x264-TBS 05/14/2018
</description>
<pubDate>Mon, 14 May 2018 06:27:34 -0400</pubDate>
```

**Comment by kaso17** [comment]
and what about the day?

**Comment by samwiseg00** [comment]
Yes the detail is in the initial issue I made.
 

 
 
 
>  
>  
>  
>    
>    
>    
>

**Comment by kaso17** [comment]
ok, should be fixed via b50733054f30297c93eb9715956a82b9f8a8ebbf, please test v0.8.994

**Comment by kaso17** [comment]
can you please share a full copy of the RSS feed (without credentials) so I can try to reproduce it?

**Comment by samwiseg00** [comment]
https://pastebin.com/raw/xpGVg5vS

**Comment by kaso17** [comment]
It seems to work fine for me.
Current EDT time of my test was 12:26, the latest release was at "09:02:22 -0400", jackett shows 3 hours ago.

**Comment by samwiseg00** [comment]
Something is still not working correctly. If you look it is not calculating the timezone when it returns results from rev. it looks like it is just striping off the timezone and adding +0200. I have tried removing it as a source and adding it back as well as verifying i am on the correct version. 

![2018-05-17_12-56-14](https://user-images.githubusercontent.com/2241731/40192327-fdfe8a68-59d1-11e8-8ca2-4e9cc60d03f2.png)

This is the same exact release from 2 different providers. They are supposed to be minuets off but they are 6 hours off. I pulled this info from jacket. This is calculated by jackett at this point. I think the source is correct but jacket is doing something to add 6hrs. 

Jacket XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
    <channel>
        <atom:link href="XXXXXXX" rel="self" type="application/rss+xml" />
        <title>RevolutionTT</title>
        <description>The Revolution has begun</description>
        <link>https://revolutiontt.me/</link>
        <language>en-us</language>
        <category>search</category>
        <image>
            <url>XXXXX</url>
            <title>RevolutionTT</title>
            <link>https://revolutiontt.me/</link>
            <description>RevolutionTT</description>
        </image>
        <item>
            <title>XXXXXX</title>
            <guid>XXXXX</guid>
            <comments>XXXX</comments>
            <pubDate>Thu, 17 May 2018 01:45:21 +0200</pubDate>
            <size>1342177280</size>
            <description>XXXXXXXX</description>
            <link>XXXXXXX</link>
            <category>5040</category>
            <category>100042</category>
            <enclosure url="XXXXXXX" />
            <torznab:attr name="category" value="5040" />
            <torznab:attr name="category" value="100042" />
            <torznab:attr name="seeders" value="8" />
            <torznab:attr name="peers" value="8" />
            <torznab:attr name="minimumratio" value="1" />
            <torznab:attr name="minimumseedtime" value="172800" />
        </item>
    </channel>
</rss>


<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
    <channel>
        <atom:link href="XXXX" />
        <title>RARBG</title>
        <description>RARBG is a Public torrent site for MOVIES / TV / GENERAL</description>
        <link>https://rarbg.to/</link>
        <language>en-us</language>
        <category>search</category>
        <image>
            <url>XXXXX</url>
            <title>RARBG</title>
            <link>https://rarbg.to/</link>
            <description>RARBG</description>
        </image>
        <item>
            <title>XXXXXXX</title>
            <guid>XXXXXXX</guid>
            <comments>https://torrentapi.org/redirect_to_info.php?token=h620o49jfe&amp;p=1_5_4_9_7_8_4__c129af9cee</comments>
            <pubDate>Thu, 17 May 2018 07:37:58 +0200</pubDate>
            <size>1343883439</size>
            <description />
            <link>XXXXXXX</link>
            <category>5040</category>
            <category>100041</category>
            <enclosure url="XXXXXXX" />
            <torznab:attr name="category" value="5040" />
            <torznab:attr name="category" value="100041" />
            <torznab:attr name="rageid" value="35853" />
            <torznab:attr name="thetvdb" value="270261" />
            <torznab:attr name="imdb" value="3444938" />
            <torznab:attr name="seeders" value="15" />
            <torznab:attr name="peers" value="23" />
            <torznab:attr name="infohash" value="XXXXXXX" />
            <torznab:attr name="downloadvolumefactor" value="0" />
            <torznab:attr name="uploadvolumefactor" value="1" />
        </item>
    </channel>
</rss>
```
This is nzbhydra reading the time...
![hydra](https://user-images.githubusercontent.com/2241731/40191875-af10af9a-59d0-11e8-8beb-81a52f848f7b.png)

Source XML rev...
```xml
<rss version="2.0">
<channel>
<title>Revolution</title>
<link>https://revolutiontt.me</link>
<description>RSS Feeds - RevolutionTT</description>
<language>en-usde</language>
<copyright>Copyright ? 2004 Revolution</copyright>
<webMaster>noreply@revolutiontt.me</webMaster>
<image>
<title>Revolution</title>
<url>https://revolutiontt.me/favicon.ico</url>
<link>https://revolutiontt.me</link>
<width>16</width>
<height>16</height>
<description>RSS Feeds - RevolutionTT</description>
</image>
<item>
<title>
xxxxx
</title>
<link>
https://revolutiontt.me/download.php/9LaodsXl7X/xxxxx
</link>
<description>
Category: TV/HDx264 Size: 1.25 GB Status: 8 seeders and 0 leechers Added: 2018-05-17 01:45:21 Description: xxxxx Video Resolution: 1280x718 Video Bitrate: 4 025 Kbps Video Framerate: 59.940 Length: 00:40:36.100 Size: 1.25 GiB
</description>
<pubDate>Thu, 17 May 2018 01:45:21 -0400</pubDate>
</item>
</channel>
</rss>
```

**Comment by kaso17** [comment]
c81dd24fe7a03415154db2cc537a7bd079a410a3 added some debug output, please try the new version and post the log

**Comment by samwiseg00** [comment]
https://pastebin.com/raw/kUDGwJZn

**Comment by kaso17** [comment]
For the newest release jackett (Ice.Age.Collision.Course.2016.PLDUB.DUAL.2160p.UHD.BluRay.x265-FLAME) computed an ago of 1:25 minutes. It looks ok to me, is it showing something else in your browser?

**Comment by samwiseg00** [comment]
Ok I think I finally figured out where the issue is. Sorry for all the back and forth on this. 

The issue seems to be when you are searching for a release. When reading the RSS feed from jackett it is correct but if you do a search it is incorrect. 

Search hitting the torznab api:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="(removed)" rel="self" type="application/rss+xml" />
    <title>RevolutionTT</title>
    <description>The Revolution has begun</description>
    <link>https://revolutiontt.me/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>(removed)</url>
      <title>RevolutionTT</title>
      <link>https://revolutiontt.me/</link>
      <description>RevolutionTT</description>
    </image>
    <item>
      <title>(removed) 720p WEB x264-CookieMonster</title>
      <guid>https://revolutiontt.me/details.php?(removed)</guid>
      <comments>(removed)</comments>
      <pubDate>Tue, 22 May 2018 12:17:20 +0200</pubDate>
      <size>1041697344</size>
      <description>(removed) 720p WEB x264-CookieMonster</description>
      <link>(removed)
      <category>5040</category>
      <category>100042</category>
      <enclosure url="(removed)"
      <torznab:attr name="category" value="5040" />
      <torznab:attr name="category" value="100042" />
      <torznab:attr name="seeders" value="12" />
      <torznab:attr name="peers" value="12" />
      <torznab:attr name="minimumratio" value="1" />
      <torznab:attr name="minimumseedtime" value="172800" />
    </item>
  </channel>
</rss>
``` 
RSS feed from jacket XML
```xml
    <item>
      <title>(removed).720p.WEB.x264-CookieMonster</title>
      <guid>(removed)</guid>
      <comments>(removed)</comments>
      <pubDate>Tue, 22 May 2018 18:17:20 +0200</pubDate>
      <size>1041697344</size>
      <description>60.Minutes.S50E37.720p.WEB.x264-CookieMonster</description>
      <link>(removed)
      <category>5040</category>
      <enclosure url="(removed)"
      <torznab:attr name="category" value="5040" />
      <torznab:attr name="seeders" value="9" />
      <torznab:attr name="peers" value="9" />
    </item>
```

**Comment by kaso17** [comment]
Looking at the code it looks like the timezone is not included in the search results.
Try changing the tracker timezone config to the same timezone as the jackett server.

**Comment by samwiseg00** [comment]
That seems to resolve it. It would be nice if that was taken into aacout when doing the search.
 
 
 
>  
>    
>

**Comment by kaso17** [comment]
Most indexers assume that the local server time equals the tracker time (if no timezone is specified). It's a general assumption at this time.
