### ISSUE TITLE
Access is denied.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by timgoat** [Jackett/Jackett#3379]
Can't access any trackers via Jackett. All tests fail. I can access trackers through browser. I changed the DNS servers to Google, same result. Jackett was working fine until today. Backed up Jackett, deleted, and started from scratch. Same results. 

Using Win 7

[log.txt](https://github.com/Jackett/Jackett/files/2189733/log.txt)
![capture](https://user-images.githubusercontent.com/41165940/42651258-bddc8a3e-85c3-11e8-8920-78828f7f3f61.PNG)

**Jackett version**:  0.9.1.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by geoffsmile** [comment]
Mine is fixed... I just updated to the latest one.. v0.9.1 ^_^

https://github.com/Jackett/Jackett/releases

**Comment by flightlevel** [comment]
Duplicate of #3383 

To resolve this issue

- Stop the Jackett service
- Close the Jackett tray
- Kill every Jackett process in task manager
- From Windows Add/Remove programs Uninstall Jackett (you won't lose your trackers)
- Go to `C:\ProgramData\Jackett` and make sure there is no exe or dll files present, only config and log files should remain after uninstalling
- Download the latest Jackett release and install via the Windows installer

**Comment by timgoat** [comment]
Fix did not work. This is NOT a duplicate of #3383 

My error has nothing to do with the AutoMapper. Please read my log and post. I already tried to start over with no success. Followed the resolution posted here and still no luck.

**Comment by flightlevel** [comment]
yep that is a different issue, can't see anyone else reporting that issue

Need more info about your setup
Are you running via console or windows service?
Are you using a http/socks proxy?
When you start Jackett are you using any command arguments?
What .NET version?
Can you access these trackers using browser on the same PC with the same connection?
VPN?
Are you using a reverse proxy e.g. nginx/apache/IIS?

Your log isn't an enhanced log and it is truncated. Need a full enhanced log i.e. start Jackett from console with `JackettConsole.exe -t -l` then click test on one of the indexers and provide the full log from startup

**Comment by timgoat** [comment]
Windows service
No
No
4.7.1
Yes
No
No

I followed your instructions and they worked fine. Log is attached. 

[log.txt](https://github.com/Jackett/Jackett/files/2196077/log.txt)

When I start using the windows service, i get the error. log is attached.

[log.txt](https://github.com/Jackett/Jackett/files/2196079/log.txt)

Could there be a problem with the service?

**Comment by flightlevel** [comment]
![image](https://user-images.githubusercontent.com/9430010/42809448-0a20b77e-89f9-11e8-8e31-10b91ff37b90.png)

![image](https://user-images.githubusercontent.com/9430010/42809483-17fded94-89f9-11e8-8f2c-41b22e3ec4f0.png)

What settings have you got on these two screens?
Error indicates that you haven't got access
http://geekswithblogs.net/technetbytes/archive/2011/10/12/147281.aspx

**Comment by timgoat** [comment]
I have the same exact settings

**Comment by flightlevel** [comment]
Can't reproduce this, suspect its an environment issue
If you google `System.Security.Cryptography.CryptographicException: Access is denied.` they give you suggestions on the problem, try those and see how you go

**Comment by timgoat** [comment]
All of the info was above my skillset. So instead, I just made a basic task in Windows Task Schedule. Made it hidden and to start whether I'm logged in or not. So basically it's a cheap and dirty alternative to the service

**Comment by flightlevel** [comment]
That will work, other alternative is to uninstall and then reinstall but don't tick install as service. Then right click on the tray icon & tick auto start on boot
