### ISSUE TITLE
[hdchina] Exception (hdchina): Got redirected to another domain. Try changing the indexer URL to http://hdchina.org/.: Parse error (Test)

### ISSUE THREAD

**Issue by yimingzhaomath** [Jackett/Jackett#4715]
Looks like the tracker HDChina.org now throws an error. Tried using both http and https. Didn't fix the problem. The website HDChina.org is reachable using browser.

Can you please look into it?

**Comment by garfield69** [comment]
It looks like hdchina upgraded their login panel from using a simple text image captcha, to now using a full cloudflare recaptcha, for which there is no automated solution.

The current method to bypass this is to switch to using the cookie method, which I have implemented with Jackett pre-release v0.10.790.

However since I don't have a login for this site, I cannot test it, and registration for hdchina is 
 currently invitation only.

So if you have an invite send it to garfieldsixtynine @ gmail.com and I can complete the testing.
In any case try 0.10.790 and hopefully this resolves the issue, let me know how it goes.

**Comment by yimingzhaomath** [comment]
Looks like it's still throwing the same error. I do have an invite, but the site is not allowing us to send out invites at the moment. I will send it once I can.

**Comment by yimingzhaomath** [comment]
@garfield69  Invitation sent. Please check.

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
I cannot replicate your problem.
I added the HDChina indexer, followed the cookie instructions, and pasted the whole cookie string and clicked OKAY.
Now I can search for torrents.
![image](https://user-images.githubusercontent.com/6933240/53293078-126a7e00-3832-11e9-82ef-fe1d9a56e24e.png)

![image](https://user-images.githubusercontent.com/6933240/53293072-fb2b9080-3831-11e9-8a3d-ce8db8e9d1ef.png)

Perhaps you could try using your Jackett dashboard to trash your hdchina indexer and start afresh by adding it anew.
Let me know how you go.

**Comment by yimingzhaomath** [comment]
It works now! Thank you for the help.
