### ISSUE TITLE
After autoupgrade to v.0.11.340 (or v.0.11.349), jackett no longer runs..

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5285]
Jacket auto upgraded to v.0.11.340 (core version on Linux), which went smoothly.
However jackett no longer runs.. Refer to the end of the run log below:
(removed yml updates to shorten log)
```
May 16 08:47:17 npi jackett[29353]: 05-16 08:47:17 Info Starting Jackett v0.11.340.0
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info Environment version: 4.0.30319.42000 (/opt/Jackett/)
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info OS version: Unix 4.14.52.0 (64bit OS) (64bit process)
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info Jackett variant: CoreLinuxArm64
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info App config/log directory: /home/qbt/.config/Jackett
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info issue: Ubuntu 16.04.6 LTS \n \l
May 16 08:47:27 npi jackett[29353]: 05-16 08:47:27 Info Using HTTP Client: HttpWebClient2NetCore
May 16 08:47:33 npi jackett[29353]: 05-16 08:47:33 Info Loading Cardigann definitions from: /home/qbt/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/Jackett/Definitions
.
May 16 08:47:44 npi jackett[29353]: 05-16 08:47:44 Info Adding aggregate indexer
May 16 08:47:44 npi jackett[29353]: 05-16 08:47:44 Info Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.11.340-636935931798808498
May 16 08:47:48 npi jackett[29353]: Hosting environment: Production
May 16 08:47:48 npi jackett[29353]: Content root path: /opt/Jackett/Content
May 16 08:47:48 npi jackett[29353]: Now listening on: http://[::]:49117
May 16 08:47:48 npi jackett[29353]: Application started. Press Ctrl+C to shut down.
May 16 09:01:13 npi jackett[29353]: 05-16 09:01:13 Error System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
May 16 09:01:13 npi jackett[29353]: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly mani
fest.
May 16 09:01:13 npi jackett[29353]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
May 16 09:01:13 npi jackett[29353]:    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
May 16 09:01:13 npi jackett[29353]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 
29
May 16 09:01:13 npi jackett[29353]: System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expe
cted to contain an assembly manifest.
May 16 09:01:13 npi jackett[29353]: File name: 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
May 16 09:01:13 npi jackett[29353]:  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
May 16 09:01:13 npi jackett[29353]: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly mani
fest.
May 16 09:01:13 npi jackett[29353]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
May 16 09:01:13 npi jackett[29353]:    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 16 09:01:13 npi jackett[29353]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
May 16 09:01:13 npi jackett[29353]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 
29
May 16 09:01:13 npi jackett[29353]: System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expe
cted to contain an assembly manifest.
May 16 09:01:13 npi jackett[29353]: File name: 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
.
.
.
.
.

May 16 09:02:34 npi jackett[29353]: 05-16 09:02:34 Error System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
May 16 09:02:34 npi jackett[29353]: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly mani
fest.
May 16 09:02:34 npi jackett[29353]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
May 16 09:02:34 npi jackett[29353]:    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
May 16 09:02:34 npi jackett[29353]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 
29
May 16 09:02:34 npi jackett[29353]: System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expe
cted to contain an assembly manifest.
May 16 09:02:34 npi jackett[29353]: File name: 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
May 16 09:02:34 npi jackett[29353]:  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
May 16 09:02:34 npi jackett[29353]: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly mani
fest.
May 16 09:02:34 npi jackett[29353]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
May 16 09:02:34 npi jackett[29353]:    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 16 09:02:34 npi jackett[29353]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
May 16 09:02:34 npi jackett[29353]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 
29
May 16 09:02:34 npi jackett[29353]: System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expe
cted to contain an assembly manifest.
May 16 09:02:34 npi jackett[29353]: File name: 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by rrrevin** [comment]
Extra info..

After an autoupdate to 340, the Microsoft.CodeAnalysis.CSharp.dll file is 0 bytes, empty.
After a manual install of 340, the Microsoft.CodeAnalysis.CSharp.dll file is 4681136 bytes.

Checking the autoupdate logs (below), there is ZERO mention of Microsoft.CodeAnalysis.CSharp.dll being upgraded. This error only appeared after autoupdating to 340.

Does autoupdate take it's files from the same place as the manual installs (https://github.com/Jackett/Jackett/releases/download/v0.11.340/Jackett.Binaries.LinuxARM64.tar.gz)?

**Comment by neuman1812** [comment]
Same issue here after auto-update  
```
May 17 14:45:26 media_pi systemd[1]: Started Jackett Daemon.
May 17 14:45:26 media_pi jackett[3667]: Failed to load L�u#001��u#001�f�v�f�v#034�u#001��u#001��u#001D�u#001, error: /opt/jackett/libhostfxr.so: Unable to run arch-specific checks
May 17 14:45:26 media_pi jackett[3667]: The library libhostfxr.so was found, but loading it from /opt/jackett/libhostfxr.so failed
May 17 14:45:26 media_pi jackett[3667]:   - Installing .NET Core prerequisites might help resolve this problem.
May 17 14:45:26 media_pi jackett[3667]:      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
May 17 14:45:26 media_pi systemd[1]: jackett.service: Main process exited, code=exited, status=130/n/a
May 17 14:45:26 media_pi systemd[1]: jackett.service: Unit entered failed state.
May 17 14:45:26 media_pi systemd[1]: jackett.service: Failed with result 'exit-code'.
^C
pi@media_pi:~ $ cd /home/jackett/.config
```



Update log : https://hastebin.com/timebewuqe.sql

**Comment by tijmenvn** [comment]
Having the exact same issue here

**Comment by rrrevin** [comment]
Happened again on the auto update to 349.

This time a different file is zero bytes; Microsoft.AspNetCore.Authentication.Abstractions.dll
Something is causing the update to write a zero byte file?

Here is a reverse modified time listing of the folder. Notice the last file updated (which is the file that is now zero bytes) has a time stamp that matches the exact same timestamp in the update log from syslog (listed below).

```
[2022 root Jackett]$ ls -lrt | tail -20
-rw-r--r-- 1 qbt qbt  1208832 May 19 10:35 Jackett.Common.dll
-rw-r--r-- 1 qbt qbt   817664 May 19 10:35 AngleSharp.dll
-rw-r--r-- 1 qbt qbt  1083984 May 19 10:35 libdbgshim.so
-rw-r--r-- 1 qbt qbt    49152 May 19 10:35 BencodeNET.dll
-rw-r--r-- 1 qbt qbt    20352 May 19 10:35 jackett.pdb
-rw-r--r-- 1 qbt qbt   745472 May 19 10:35 libhostpolicy.so
-rw-r--r-- 1 qbt qbt   196608 May 19 10:35 ICSharpCode.SharpZipLib.dll
-rwxr--r-- 1 qbt qbt   119216 May 19 10:35 jackett
-rw-r--r-- 1 qbt qbt     3620 May 19 10:35 JackettUpdater.pdb
-rw-r--r-- 1 qbt qbt   854528 May 19 10:35 CsQuery.dll
-rw-r--r-- 1 qbt qbt   724040 May 19 10:35 libcoreclrtraceptprovider.so
-rw-r--r-- 1 qbt qbt   326144 May 19 10:35 JackettUpdater.dll
-rw-r--r-- 1 qbt qbt   246736 May 19 10:35 libMonoPosixHelper.so
-rw-r--r-- 1 qbt qbt   264968 May 19 10:35 Jackett.Common.pdb
-rw-r--r-- 1 qbt qbt  2832616 May 19 10:35 libmscordbi.so
-rw-r--r-- 1 qbt qbt   716768 May 19 10:35 libhostfxr.so
-rw-r--r-- 1 qbt qbt   647576 May 19 10:35 libsos.so
-rw-r--r-- 1 qbt qbt    18047 May 19 10:35 LICENSE
-rw-r--r-- 1 qbt qbt  3909416 May 19 10:35 libmscordaccore.so
-rw-r--r-- 1 qbt qbt        0 May 19 10:35 Microsoft.AspNetCore.Authentication.Abstractions.dll
```

Could this mean the file was either overwritten as a zero byte file, or could not be updated and caused a segv resulting in a zero byte file?

Log (stripped out all the yml updates to shorten log):
```
May 19 10:34:24 npi jackett[31593]: 05-19 10:34:24 Info New release found.  Current: v0.11.340 New: v0.11.349
May 19 10:35:35 npi jackett[31593]: 05-19 10:35:35 Info Starting updater: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater --Path "/opt/Jackett" --Type "Console" --Args " --NoRestart" --KillPids "3
1593" --NoRestart
May 19 10:35:35 npi jackett[31593]: 05-19 10:35:35 Info Updater started process id: 20501
May 19 10:35:40 npi jackett[31593]: 05-19 10:35:40 Info Jackett Updater v0.11.349.0
May 19 10:35:40 npi jackett[31593]: 05-19 10:35:40 Info Options "--Path" "/opt/Jackett" "--Type" "Console" "--Args" " --NoRestart" "--KillPids" "31593" "--NoRestart"
May 19 10:35:40 npi jackett[31593]: 05-19 10:35:40 Info Jackett variant: CoreLinuxArm64
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to remove: /opt/Jackett/DateTimeRoutines.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Deleted /opt/Jackett/DateTimeRoutines.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to remove: /opt/Jackett/jackett.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Deleted /opt/Jackett/jackett.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to remove: /opt/Jackett/JackettUpdater.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Deleted /opt/Jackett/JackettUpdater.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to remove: /opt/Jackett/Jackett.Common.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Deleted /opt/Jackett/Jackett.Common.pdb
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to remove: /opt/Jackett/jackett
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Deleted /opt/Jackett/jackett
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Finding files in: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info 634 update files found
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy AngleSharp.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/AngleSharp.dll to destination: /opt/Jackett/AngleSharp.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied AngleSharp.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy Autofac.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Autofac.dll to destination: /opt/Jackett/Autofac.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied Autofac.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy Autofac.Extensions.DependencyInjection.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Autofac.Extensions.DependencyInj
ection.dll to destination: /opt/Jackett/Autofac.Extensions.DependencyInjection.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied Autofac.Extensions.DependencyInjection.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy AutoMapper.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/AutoMapper.dll to destination: /opt/Jackett/AutoMapper.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied AutoMapper.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy BencodeNET.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/BencodeNET.dll to destination: /opt/Jackett/BencodeNET.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied BencodeNET.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy CloudFlareUtilities.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/CloudFlareUtilities.dll to destination: /opt/Jacket
t/CloudFlareUtilities.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied CloudFlareUtilities.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy CommandLine.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/CommandLine.dll to destination: /opt/Jackett/CommandLine.dl
l
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied CommandLine.dll
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy animate.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/animate.css to destination: /opt/Jackett/Content/animat
e.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied animate.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy binding_dark.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/binding_dark.png to destination: /opt/Jackett/Cont
ent/binding_dark.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied binding_dark.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy bootstrap.min.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/bootstrap/bootstrap.min.css to destination: /opt/
Jackett/Content/bootstrap/bootstrap.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied bootstrap.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy bootstrap.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/bootstrap/bootstrap.min.js to destination: /opt/Ja
ckett/Content/bootstrap/bootstrap.min.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied bootstrap.min.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy common.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/common.js to destination: /opt/Jackett/Content/common.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied common.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy congruent_outline.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/congruent_outline.png to destination: /opt/Ja
ckett/Content/congruent_outline.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied congruent_outline.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy crissXcross.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/crissXcross.png to destination: /opt/Jackett/Conten
t/crissXcross.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied crissXcross.png
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy bootstrap-multiselect.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/css/bootstrap-multiselect.css to destinat
ion: /opt/Jackett/Content/css/bootstrap-multiselect.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied bootstrap-multiselect.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy font-awesome.min.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/css/font-awesome.min.css to destination: /opt/
Jackett/Content/css/font-awesome.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied font-awesome.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy jquery.dataTables.min.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/css/jquery.dataTables.min.css to destinat
ion: /opt/Jackett/Content/css/jquery.dataTables.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied jquery.dataTables.min.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy custom_mobile.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/custom_mobile.css to destination: /opt/Jackett/Co
ntent/custom_mobile.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied custom_mobile.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy custom.css from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/custom.css to destination: /opt/Jackett/Content/custom.c
ss
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied custom.css
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy custom.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/custom.js to destination: /opt/Jackett/Content/custom.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied custom.js
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy favicon.ico from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/favicon.ico to destination: /opt/Jackett/Content/favico
n.ico
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied favicon.ico
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy fontawesome-webfont.eot from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/fontawesome-webfont.eot to destinatio
n: /opt/Jackett/Content/fonts/fontawesome-webfont.eot
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied fontawesome-webfont.eot
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy fontawesome-webfont.svg from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/fontawesome-webfont.svg to destinatio
n: /opt/Jackett/Content/fonts/fontawesome-webfont.svg
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied fontawesome-webfont.svg
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy fontawesome-webfont.ttf from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/fontawesome-webfont.ttf to destinatio
n: /opt/Jackett/Content/fonts/fontawesome-webfont.ttf
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied fontawesome-webfont.ttf
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy fontawesome-webfont.woff from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/fontawesome-webfont.woff to destinat
ion: /opt/Jackett/Content/fonts/fontawesome-webfont.woff
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Copied fontawesome-webfont.woff
May 19 10:35:41 npi jackett[31593]: 05-19 10:35:41 Info Attempting to copy fontawesome-webfont.woff2 from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/fontawesome-webfont.woff2 to destin
ation: /opt/Jackett/Content/fonts/fontawesome-webfont.woff2
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:41 Info Copied fontawesome-webfont.woff2
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy FontAwesome.otf from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/FontAwesome.otf to destination: /opt/Jackett/
Content/fonts/FontAwesome.otf
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied FontAwesome.otf
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy glyphicons-halflings-regular.eot from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/glyphicons-halflings-regular
.eot to destination: /opt/Jackett/Content/fonts/glyphicons-halflings-regular.eot
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied glyphicons-halflings-regular.eot
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy glyphicons-halflings-regular.svg from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/glyphicons-halflings-regular
.svg to destination: /opt/Jackett/Content/fonts/glyphicons-halflings-regular.svg
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied glyphicons-halflings-regular.svg
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy glyphicons-halflings-regular.ttf from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/glyphicons-halflings-regular
.ttf to destination: /opt/Jackett/Content/fonts/glyphicons-halflings-regular.ttf
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied glyphicons-halflings-regular.ttf
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy glyphicons-halflings-regular.woff from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/glyphicons-halflings-regula
r.woff to destination: /opt/Jackett/Content/fonts/glyphicons-halflings-regular.woff
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied glyphicons-halflings-regular.woff
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy glyphicons-halflings-regular.woff2 from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/fonts/glyphicons-halflings-regul
ar.woff2 to destination: /opt/Jackett/Content/fonts/glyphicons-halflings-regular.woff2
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied glyphicons-halflings-regular.woff2
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy sort_asc_disabled.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/images/sort_asc_disabled.png to destination: 
/opt/Jackett/Content/images/sort_asc_disabled.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied sort_asc_disabled.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy sort_asc.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/images/sort_asc.png to destination: /opt/Jackett/Conte
nt/images/sort_asc.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied sort_asc.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy sort_both.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/images/sort_both.png to destination: /opt/Jackett/Con
tent/images/sort_both.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied sort_both.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy sort_desc_disabled.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/images/sort_desc_disabled.png to destination
: /opt/Jackett/Content/images/sort_desc_disabled.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied sort_desc_disabled.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy sort_desc.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/images/sort_desc.png to destination: /opt/Jackett/Con
tent/images/sort_desc.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied sort_desc.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy index.html from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/index.html to destination: /opt/Jackett/Content/index.ht
ml
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied index.html
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy jacket_medium.png from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/jacket_medium.png to destination: /opt/Jackett/Co
ntent/jacket_medium.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied jacket_medium.png
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy api.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/api.js to destination: /opt/Jackett/Content/libs/api.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied api.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy bootstrap-multiselect.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/bootstrap-multiselect.js to destinati
on: /opt/Jackett/Content/libs/bootstrap-multiselect.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied bootstrap-multiselect.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy bootstrap-notify.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/bootstrap-notify.js to destination: /opt/J
ackett/Content/libs/bootstrap-notify.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied bootstrap-notify.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy filesize.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/filesize.min.js to destination: /opt/Jackett/C
ontent/libs/filesize.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied filesize.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy handlebars.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/handlebars.min.js to destination: /opt/Jacke
tt/Content/libs/handlebars.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied handlebars.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy handlebarsextend.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/handlebarsextend.js to destination: /opt/J
ackett/Content/libs/handlebarsextend.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied handlebarsextend.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy handlebarsmoment.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/handlebarsmoment.js to destination: /opt/J
ackett/Content/libs/handlebarsmoment.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied handlebarsmoment.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy jquery.dataTables.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/jquery.dataTables.min.js to destinati
on: /opt/Jackett/Content/libs/jquery.dataTables.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied jquery.dataTables.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy jquery.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/jquery.min.js to destination: /opt/Jackett/Conte
nt/libs/jquery.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied jquery.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy moment.min.js from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/libs/moment.min.js to destination: /opt/Jackett/Conte
nt/libs/moment.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied moment.min.js
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy login.html from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Content/login.html to destination: /opt/Jackett/Content/login.ht
ml
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied login.html
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy CsQuery.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/CsQuery.dll to destination: /opt/Jackett/CsQuery.dll
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied CsQuery.dll
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy DateTimeRoutines.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/DateTimeRoutines.dll to destination: /opt/Jackett/Date
TimeRoutines.dll
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied DateTimeRoutines.dll
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy DateTimeRoutines.pdb from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/DateTimeRoutines.pdb to destination: /opt/Jackett/Date
TimeRoutines.pdb
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied DateTimeRoutines.pdb
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy ICSharpCode.SharpZipLib.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/ICSharpCode.SharpZipLib.dll to destination: /op
t/Jackett/ICSharpCode.SharpZipLib.dll
May 19 10:35:42 npi jackett[31593]: 05-19 10:35:42 Info Copied ICSharpCode.SharpZipLib.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:42 Info Attempting to copy install_service_systemd.sh from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/install_service_systemd.sh to destination: /opt/
Jackett/install_service_systemd.sh
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied install_service_systemd.sh
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy jackett from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/jackett to destination: /opt/Jackett/jackett
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied jackett
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy Jackett.Common.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Jackett.Common.dll to destination: /opt/Jackett/Jackett.
Common.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied Jackett.Common.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy Jackett.Common.pdb from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/Jackett.Common.pdb to destination: /opt/Jackett/Jackett.
Common.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied Jackett.Common.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy jackett.deps.json from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/jackett.deps.json to destination: /opt/Jackett/jackett.de
ps.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied jackett.deps.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy jackett.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/jackett.dll to destination: /opt/Jackett/jackett.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied jackett.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy jackett.pdb from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/jackett.pdb to destination: /opt/Jackett/jackett.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied jackett.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy jackett.runtimeconfig.json from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/jackett.runtimeconfig.json to destination: /opt/
Jackett/jackett.runtimeconfig.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied jackett.runtimeconfig.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy JackettUpdater from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater to destination: /opt/Jackett/JackettUpdater
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied JackettUpdater
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy JackettUpdater.deps.json from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater.deps.json to destination: /opt/Jack
ett/JackettUpdater.deps.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied JackettUpdater.deps.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy JackettUpdater.dll from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater.dll to destination: /opt/Jackett/JackettU
pdater.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied JackettUpdater.dll
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy JackettUpdater.pdb from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater.pdb to destination: /opt/Jackett/JackettU
pdater.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied JackettUpdater.pdb
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy JackettUpdater.runtimeconfig.json from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/JackettUpdater.runtimeconfig.json to dest
ination: /opt/Jackett/JackettUpdater.runtimeconfig.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied JackettUpdater.runtimeconfig.json
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libclrjit.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libclrjit.so to destination: /opt/Jackett/libclrjit.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied libclrjit.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libcoreclr.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libcoreclr.so to destination: /opt/Jackett/libcoreclr.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied libcoreclr.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libcoreclrtraceptprovider.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libcoreclrtraceptprovider.so to destination: /
opt/Jackett/libcoreclrtraceptprovider.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied libcoreclrtraceptprovider.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libdbgshim.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libdbgshim.so to destination: /opt/Jackett/libdbgshim.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied libdbgshim.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libhostfxr.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libhostfxr.so to destination: /opt/Jackett/libhostfxr.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Copied libhostfxr.so
May 19 10:35:43 npi jackett[31593]: 05-19 10:35:43 Info Attempting to copy libhostpolicy.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libhostpolicy.so to destination: /opt/Jackett/libhostpolic
y.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Copied libhostpolicy.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Attempting to copy libMonoPosixHelper.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libMonoPosixHelper.so to destination: /opt/Jackett/li
bMonoPosixHelper.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Copied libMonoPosixHelper.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Attempting to copy libmscordaccore.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libmscordaccore.so to destination: /opt/Jackett/libmscor
daccore.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Copied libmscordaccore.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Attempting to copy libmscordbi.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libmscordbi.so to destination: /opt/Jackett/libmscordbi.so
May 19 10:35:44 npi systemd[1]: jackett.service: Main process exited, code=killed, status=11/SEGV
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Copied libmscordbi.so
May 19 10:35:44 npi jackett[31593]: 05-19 10:35:44 Info Attempting to copy libsos.so from source: /tmp/JackettUpdate-v0.11.349-636938589095686851/Jackett/libsos.so to destination: /opt/Jackett/libsos.so
May 19 10:35:45 npi systemd[1]: jackett.service: Unit entered failed state.
May 19 10:35:45 npi systemd[1]: jackett.service: Failed with result 'signal'.
May 19 10:35:50 npi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
May 19 10:35:50 npi systemd[1]: Stopped Jackett Daemon.
May 19 10:35:50 npi systemd[1]: Started Jackett Daemon.
May 19 10:35:55 npi jackett[20525]: 05-19 10:35:55 Info Starting Jackett v0.11.349.0
May 19 10:35:59 npi jackett[20525]: 05-19 10:35:59 Error System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToke
n=adb9793829ddae60'. The module was expected to contain an assembly manifest.
May 19 10:35:59 npi jackett[20525]: File name: 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
May 19 10:35:59 npi jackett[20525]:    at Jackett.Server.Program.Main(String[] args)
May 19 10:35:59 npi jackett[20525]:  System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
 The module was expected to contain an assembly manifest.
May 19 10:35:59 npi jackett[20525]: File name: 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
May 19 10:35:59 npi jackett[20525]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
May 19 10:35:59 npi jackett[20525]:    at Jackett.Server.Program.Main(String[] args)
```

**Comment by DeathIsUnknown** [comment]
Same issue on my end!

`journalctl -u jackett.service`:
```
May 21 00:10:35 RockPro jackett[10179]: 05-21 00:10:35 Info Starting Jackett v0.11.349.0
May 21 00:10:37 RockPro jackett[10179]: 05-21 00:10:37 Error System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Http, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The module was expected to contain an assembly manifest.
May 21 00:10:37 RockPro jackett[10179]: File name: 'Microsoft.AspNetCore.Http, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
May 21 00:10:37 RockPro jackett[10179]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
May 21 00:10:37 RockPro jackett[10179]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
May 21 00:10:37 RockPro jackett[10179]:    at Jackett.Server.Program.Main(String[] args)
May 21 00:10:37 RockPro jackett[10179]:  System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Http, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The module was expected to contain an assembly manifest.
May 21 00:10:37 RockPro jackett[10179]: File name: 'Microsoft.AspNetCore.Http, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
May 21 00:10:37 RockPro jackett[10179]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
May 21 00:10:37 RockPro jackett[10179]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
May 21 00:10:37 RockPro jackett[10179]:    at Jackett.Server.Program.Main(String[] args)
May 21 00:15:58 RockPro systemd[1]: Stopping Jackett Daemon (DietPi)...
```

`ls -a /opt/jackett`:
```
...
-rw-r--r-- 1 jackett jackett    19832 May 19 22:45 Microsoft.AspNetCore.Html.Abstractions.dll
-rw-r--r-- 1 jackett jackett    76152 May 19 22:45 Microsoft.AspNetCore.Http.Abstractions.dll
-rw-r--r-- 1 jackett jackett        0 May 19 22:45 Microsoft.AspNetCore.Http.dll
-rw-r--r-- 1 jackett jackett    38776 May 18 09:04 Microsoft.AspNetCore.Http.Extensions.dll
-rw-r--r-- 1 jackett jackett    32120 May 18 09:04 Microsoft.AspNetCore.Http.Features.dll
...
```

Notice `Microsoft.AspNetCore.Http.dll` and all files alphabetically prior have been modified on **May 19 22:45** and the following files have not yet been modified (still on **May 18 09:04**). Based on this, it looks like the auto-updater is encountering an error and aborting before all files have been replaced. Could this be because systemd restarts Jackett before the updater has finished?

I've been trying to debug the issue over on the DietPi repo, thinking it was an issue there https://github.com/MichaIng/DietPi/issues/2593.

**Comment by DeathIsUnknown** [comment]
Duplicate of https://github.com/Jackett/Jackett/issues/5208?

**Comment by flightlevel** [comment]
Duplicate of #5208

**Comment by garfield69** [comment]
fix is available with stable jackett 0.12.898. but you will need to install manually and run the systemd install script anew.

1. open a terminal and shutdown the jackett service using `systemctl stop jackett.service`
2. download and extract the linux package that applies to your platform from https://github.com/Jackett/Jackett/releases/tag/v0.12.898
3. copy or move/replace all the files from the Jackett folder in the downloaded/extracted package to where ever you have previously put the jackett binaries. Typical locations are `/opt/Jackett` or `~/Jackett`
4. cd to your Jackett binary folder and install the service with `sudo ./install_service_systemd.sh` 
this will start the service (if it ran successfully)
5. access your jackett dashboard with your browser and untick the Disable auto Update check box and press the Apply Server Settings button.

**Comment by tijmenvn** [comment]
I have to edit the `install_service_systemd.sh` file everytime I update with the `Environment=XDG_CONFIG_HOME=/path/to/folder` line, since I am running as a user without home folder. I assume I can still not use the auto-update feature in that case, that right?

**Comment by garfield69** [comment]
@tijmenvn  the install script you are talking about creates a profile in the systemd folder.
while its true that after an auto-update this script would be reset without your environment update, the profile in the systemd folder is only ever replaced when you manually run the install script, the auto-updater does not run this script itself.
so I think you can have the auto-updated enabled and take advantage of the updates.
It is only when you need to run the install script again to replace the systemd profile (a rare event), that you will need to add that environment statement in beforehand.
