### ISSUE TITLE
[beyond-hd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Rouzax** [Jackett/Jackett#6281]
![image](https://user-images.githubusercontent.com/4103090/68038368-0ccf0d00-fcca-11e9-92ac-ea12d4a46793.png)

```
2019-11-01 16:11:27.6158 Error CardigannIndexer (beyond-hd): Error while parsing row '
<tr id="commenthidden37932" style="display: none; background-color: #111111;">
	<td colspan="11" id="commentcell37932" style="display: none; background-color: #111111;">
		<div class="hd-table">
			<div class="hd-full">
				<div id="paddingtorrent37932" style="padding-left: 5px; padding-right: 0px;">
					<div comment="37932" id="commenttorrentlist37932">
					</div>
				</div>
			</div>
		</div>
	</td>
</tr>':

System.Exception: Error while parsing field=title, selector=a.torrent-name, value=<null>: Selector "a.torrent-name" didn't match 
<tr id="commenthidden37932" style="display: none; background-color: #111111;">
	<td colspan="11" id="commentcell37932" style="display: none; background-color: #111111;">
		<div class="hd-table">
			<div class="hd-full">
				<div id="paddingtorrent37932" style="padding-left: 5px; padding-right: 0px;">
					<div comment="37932" id="commenttorrentlist37932">
					</div>
				</div>
			</div>
		</div>
	</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext() 
2019-11-01 16:11:27.6471 Error CardigannIndexer (beyond-hd): Error while parsing row '
<tr id="commenthidden37925" style="display: none; background-color: #111111;">
	<td colspan="11" id="commentcell37925" style="display: none; background-color: #111111;">
		<div class="hd-table">
			<div class="hd-full">
				<div id="paddingtorrent37925" style="padding-left: 5px; padding-right: 0px;">
					<div comment="37925" id="commenttorrentlist37925">
					</div>
				</div>
			</div>
		</div>
	</td>
</tr>':

System.Exception: Error while parsing field=title, selector=a.torrent-name, value=<null>: Selector "a.torrent-name" didn't match 
<tr id="commenthidden37925" style="display: none; background-color: #111111;">
	<td colspan="11" id="commentcell37925" style="display: none; background-color: #111111;">
		<div class="hd-table">
			<div class="hd-full">
				<div id="paddingtorrent37925" style="padding-left: 5px; padding-right: 0px;">
					<div comment="37925" id="commenttorrentlist37925">
					</div>
				</div>
			</div>
		</div>
	</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext() 
```

Jackett Version 0.12.907.0

**Comment by garfield69** [comment]
works for me. 
your log snippet shows the same error as #6293 that you opened 4 days ago, which has already been fixed.
what platform are you running jackett on?

**Comment by Rouzax** [comment]
Windows 2019
You also have the classic theme?

**Comment by garfield69** [comment]
yes. it's the only theme supported by the indexer (as I mentioned in #6293).
I tested this just now on my windows 10.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by garfield69** [comment]
did you install jackett as a service or are you simply launching jackett manually?

**Comment by Rouzax** [comment]
It's running as a service
attached is the log
[log.txt](https://github.com/Jackett/Jackett/files/3799199/log.txt)

**Comment by Rouzax** [comment]
When I go the the login page I see the additional captcha field
![image](https://user-images.githubusercontent.com/4103090/68048714-760e4a80-fce1-11e9-8fbc-1959856292fb.png)

**Comment by garfield69** [comment]
yes. it looks like they have changed the login page, and the enhanced log you provided shows that this is the reason you are getting the login-redirected, as the jackett login attempts were not successful.
I guess my login worked because my cookies have not yet expired so I'm net getting challenged.

standby for a fix announcement.

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.910
you will need to edit your beyond-hd config with the jackett dashboard wrench icon to login with the the captcha solution, and from now on, you may need to do this intermittently whenever the cookies expire.

**Comment by Rouzax** [comment]
Looking good
![image](https://user-images.githubusercontent.com/4103090/68051246-42362380-fce7-11e9-9ad5-4ecbef9694ff.png)

It looks like the new theme does also work.

**Comment by carlosabias** [comment]
I keep getting the same problem, have done everything I can think of, and still get redirected with BeyondHD

[log.txt](https://github.com/Jackett/Jackett/files/3827508/log.txt)

**Comment by carlosabias** [comment]
How did you fix it @Rouzax ?

**Comment by Rouzax** [comment]
It is fixed in the Develop branch. Not yet in the master.

**Comment by Rouzax** [comment]
You sure you have the latest version?

**Comment by shaggyblue** [comment]
@carlosabias I had to disable MFA to get mine to work.

`<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        **<meta http-equiv="refresh" content="0;url=https://beyond-hd.me/twostep/needed" />**

        <title>Redirecting to https://beyond-hd.me/twostep/needed</title>
    </head>
    <body>
        **Redirecting to <a href="https://beyond-hd.me/twostep/needed">https://beyond-hd.me/twostep/needed</a>.**
    </body>
</html>`

**Comment by danaimone** [comment]
Still an issue if you have 2FA authorization. Can be avoided by disabling, but a more elegant solution could be proposed.

**Comment by garfield69** [comment]
Feel free to contribute and raise a PR for #3345
