### ISSUE TITLE
crashing from an OutOfMemoryException

### ISSUE THREAD

**Issue by TomW1605** [Jackett/Jackett#6377]
Jackett is, apparently randomly, crashing from an OutOfMemoryException:

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()

all the other entries in the log are HTML fragments of what looks like search resaults.

here is a bit of the log file, all 5 log files are full of the HTML and they get replaced very quickly
https://pastebin.com/V6gGpkEn

**Jackett version**:  0.12.993.0
**Mono version**: N/A

**Comment by garfield69** [comment]
unfortunately nothing in the log fragment you provided identifies the indexer that was in use that seems to be generating all those info messages.
if you can manage to identify the indexer then I can at least begin to have a look at the issue.

**Comment by TomW1605** [comment]
please find attached the rest of the log files. im not sure what to look for.

[log.txt.20191117.00371.txt](https://github.com/Jackett/Jackett/files/3855293/log.txt.20191117.00371.txt)
[log.txt.20191117.00372.txt](https://github.com/Jackett/Jackett/files/3855294/log.txt.20191117.00372.txt)
[log.txt.20191117.00373.txt](https://github.com/Jackett/Jackett/files/3855295/log.txt.20191117.00373.txt)
[log.txt.20191117.00374.txt](https://github.com/Jackett/Jackett/files/3855296/log.txt.20191117.00374.txt)
[log.txt.20191117.00375.txt](https://github.com/Jackett/Jackett/files/3855297/log.txt.20191117.00375.txt)
[log.txt](https://github.com/Jackett/Jackett/files/3855298/log.txt)

**Comment by garfield69** [comment]
From what I can see in you logs, it appears that you are using the **ALL** (aggregate) indexer, so you are probably using multiple indexers with Sonarr or similar?
BTW, not a good idea. Recommend you take the time to load each indexer you want to use with Sonarr individually, it will improve your chances of getting results.

anyway, the logs you provided are full of only that html and nothing else :-(
but we got lucky!
one of the html segments had the following 
`<tr align="left" bgcolor="#CCCCCC"><td colspan="10" class="added_today">Added today</td></tr>`
which I recognised as belonging to **Demonoid** :-)
so I was able to test this for myself and discovered that logging for DateHeader processing was set to **Info** instead of **Debug**.
So I've changed this and it should make a difference to the amount of logging going on when using demonoid.

But I do not know if this will fix your out-of-memory issue.
try out jackett 0.12.1000 and see if that helps.

**Comment by TomW1605** [comment]
Ok after installing the update the logs are no longer spammed with HTML. I tried removing the entire from sonarr, radarr and lidarr and it stopped crashing. I have now connected them all again and am getting more errors (see below). there are several searches that I am sure are for items I have not added to any of those programs so I am assuming they are making a search to test if the tracker is available. is there any way to log the origin and key words of a search so i can see what is doing it? I think this info kind of makes since in the log anyway, `Found 522 (184 new) releases from AggregateSearch` isn’t a particularly helpful message compared to `Found 522 (184 new) releases from AggregateSearch made by Radarr for 'MovieTitle'`

if it is the other programs making a search to test the indexer then I’m not entirely sure how switching to individual entries for each indexer will help as it will just mean more searches made evry time it tests the indexer.

i am seeing 2 distinct errors in the logs. the first is:
```2019-11-20 16:09:47.0003 Error System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext() System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
```
and the second is:
```2019-11-20 16:13:01.0815 Error System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at System.Xml.Linq.XNode.ToString()
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext() System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at System.Xml.Linq.XNode.ToString()
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
```

**Comment by TomW1605** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3868287/log.txt)
also here is my full log file if that helps

**Comment by garfield69** [comment]
a good reason for not using the aggregate indexer is because if any of the jackett indexer have problems connecting or using the web sites they are scraping, then the whole response package is delayed or even aborted if the timeouts accumulate beyond what radarr is expecting (after all as far as radarr is concerned its dealing with one indexer, but behind the scenes jackett is dealing with multiple ones).
And when there are problems like this, the using the aggregate indexer makes it difficult to debug the problem.

what platform are you running jackett on, and how much memory is available?
how many indexers have you defined on jackett?

do you have may series you are tracking, are you making single searches or launching multiple series episode searches at once?
I'm just trying to get a feel for the workload you are putting radarr and jackett through.

you can see what request radarr makes by looking at the radarr logs.
you can get more details on what requests are made to jackett by enabling the enhanced logging. see the dashboard bottom section, tick the enhanced logging and click on the apply server settings.
but be warned, this will generate a lot of logging.

the latest log you updated shws that the torrent-csv indexer  is returning lots of bad gateway errors, so I would drop that indexer for now.

**Comment by TomW1605** [comment]
ok I will consider using separate indexers for each one however, to answer another question, I have 30 indexers, after removing the bad one, and 3 programs that use them so adding 90 indexers would be a trek and take a while. also, I like that I can add and remove indexers from Jackett without having to make any changes to the other programs so I would prefer to keep using the aggregate one if posable.

I am running Jackett, and all the other servers, on a windows 7 computer with 16gb of ram. unfortunately, it is the only computer I have so is not a dedicated server and sits at about 50% ram usage while idle. as mentioned earlier I have 30 indexers after removing torrent-csv and another one that was failing tests consistently.

I have several tracked series however my understanding was the Sonarr didn’t search for them until they had aired. I have not made any manual searches in the past few days when this issue has been occurring.

also, from those old logs that had the HTML it was searching for shows/movies/music I have never heard of and defiantly not ones I have monitored. I think Sonarr etc is making random searches to test the indexers availability and that might be overloading it.

I have found the search that Sonarr is making to test the indexer: http://localhost:9117/api/v2.0/indexers/all/results/torznab?t=tvsearch&cat=5000,5010,5030,5040,5050,5060,5070,5080&extended=1&apikey=(removed)&offset=0&limit=1000 
Unfortunately enabling enhanced logging produced so much output that it pushed the part where Jackett receives the request off the log.

As mentioned earlier I have removed torrent-csv and 1 other one that was failing tests so hopefully that will help but I’m not sure it will.

I am planning to upgrade my computer soon (next 3-4 months) and will then use this computer as a dedicated server. Till then I think I will set up a script to run when Jackett crashes and restart it.

Any other advice would be greatly welcomed.
Thanks

**Comment by garfield69** [comment]
IMO having 30 indexers in use for tracking tv episodes is over the top.
most of  them are going to produce duplicate entries anyway.
You would be far better off to settle for the 5 best indexers that regularly produce the episodes you are interested in, and load them on sonarr individually so it can handle the occasional web site glitches more gracefully.
You will reduce the overhead on network traffic your 30 indexers are spawning, reduce the memory load and capacity of your platform.

In any case I beleive there is little else we can do for you in this ticket.

**Comment by TomW1605** [comment]
ok thanks for the advice. can you recomend how to chose the best trackers? im quite new to torrenting so am not sure what ones are good.

would it work to chose the best 5 to add manualy and then have the rest added but only used for manual searchers?

**Comment by garfield69** [comment]
I would start by using the jackett dashboard manual search, type in the name of a series followed by the latest available SxxExx  and any particular quality your usually into, 
(for example `Castle Rock S02E07 1080p`) 
and see how many of the indexer you have return results you would be happy with.
repeat for a few more series and then choose the 5 that consistently gave you satisfactory results for all the titles you want.

**Comment by TomW1605** [comment]
ok i have added each indexer indevidualy and am still geting crashes. i think it is a difrent issue but will wait and see

**Comment by TomW1605** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3899255/log.txt)

ok now i have stoped using the agragate indexer jackett is still crashing and actualy crashing more often. i have attached a full log from start up to crash and there are some errors but nothing when it actualy crashed so im not sure what is causing it

**Comment by garfield69** [comment]
I don't see any crashes. But maybe that is because your definition of a crash is different from mine.
You are no longer seeing jackett stop running, or terminating, correct?
and the errors in your log are some of the typical ones I see commonly on my own jackett use.
 
Torrentz2 is a bad performer for you, I'd suggest dropping that one. lots of http bad gateways, of http 522 server down. Nothing you can do about this. problems at the site.

and kickasstorrent seems to throw up `An established connection was aborted by the software in your host machine` and `Authentication failed because the remote party has closed the transport stream`
those looks like network type errors. No idea what you can do about these, Im not a network support specialist.

But basically, I do not see any issued caused by jackett.

**Comment by TomW1605** [comment]
by crash i mean the survice has stoped running. then i get a bunch of notifications about failed indexers from sonarr and radarr.

**Comment by garfield69** [comment]
Fair enough.
Have you taken a look at the windows Events viewer's System log for hits on the jackett service?
if the service crashed then there should be an error code from the crash, and maybe more details.

**Comment by TomW1605** [comment]
the only events i could find related to jackett are start and stop events
from the system log:
```Log Name:      System
Source:        Service Control Manager
Date:          27/11/2019 21:06:45
Event ID:      7036
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Thomas-PC
Description:
The Jackett service entered the running state.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="16384">7036</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-27T13:06:45.754881500Z" />
    <EventRecordID>311370</EventRecordID>
    <Correlation />
    <Execution ProcessID="928" ThreadID="26072" />
    <Channel>System</Channel>
    <Computer>Thomas-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">Jackett</Data>
    <Data Name="param2">running</Data>
    <Binary>4A00610063006B006500740074002F0034000000</Binary>
  </EventData>
</Event>
```
and
```Log Name:      System
Source:        Service Control Manager
Date:          28/11/2019 07:40:20
Event ID:      7036
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Thomas-PC
Description:
The Jackett service entered the stopped state.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="16384">7036</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-27T23:40:20.484199600Z" />
    <EventRecordID>311441</EventRecordID>
    <Correlation />
    <Execution ProcessID="928" ThreadID="1536" />
    <Channel>System</Channel>
    <Computer>Thomas-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">Jackett</Data>
    <Data Name="param2">stopped</Data>
    <Binary>4A00610063006B006500740074002F0031000000</Binary>
  </EventData>
</Event>
```

and from the Application log:
```Log Name:      Application
Source:        Jackett
Date:          27/11/2019 21:06:45
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Thomas-PC
Description:
Service started successfully.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Jackett" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-27T13:06:45.000000000Z" />
    <EventRecordID>509194</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Thomas-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service started successfully.</Data>
  </EventData>
</Event>
```
and
```Log Name:      Application
Source:        Jackett
Date:          28/11/2019 07:40:20
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Thomas-PC
Description:
Service stopped successfully.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Jackett" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-27T23:40:20.000000000Z" />
    <EventRecordID>509215</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Thomas-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped successfully.</Data>
  </EventData>
</Event>
```

there is nothing between or around these events

unfortunatly this dosent provide much insight into what is hapaning

i will remove the trackers you sagest and see if that helps but i doubt it.

**Comment by garfield69** [comment]
>by crash i mean the survice has stoped running. then i get a bunch of notifications about failed indexers from sonarr and radarr.

the next time you get these notifications about failed indexers from sonarr or radarr, see if you can access the jackett dashboard from your browser. it you can, then the service is still running and the problem is not a crash but something else.
also remember that if a sonarr or radarr indexer (even one defined via jackett) takes too long to respond and times out the sonarr/radarr timer, it will flag the indexer as failing, and not use it again until the indexer is reset (usually by doing a sonarr /radarr indexer test, or restarting the sonarr/radarr service/app.

**Comment by TomW1605** [comment]
i am awair that a delay will cause a notification however i am getting one for evry one of the indexers using jackett. also when i say the eurvice has stoped running i am looking in the windows service manager and it is labled as stoped with the option to start the survice. i do some times get notifications when the survice is still running and usualy manualy retesting fixes it then but not if jackett is not running.

**Comment by garfield69** [comment]
if the service has stopped, but there are no crashes in the system events log, then the only other thing that could have happened is that the service was stopped deliberately by the updater process and for some reason not started back up again.
so maybe your next avenue of research should be to examine the update.txt files in the jackett programdata folder to see if there are signs there that something is not working with the restart?

**Comment by TomW1605** [comment]
ok i am leaving soon to go away for the weekend so what i will do is turn off auto update and see if that helps. when i get back i will have a look in the folder and see if there is anything there but if it dosent crash all weekend then i will assum it is the update that is the problem and try and debug it from there.

**Comment by ngosang** [comment]
There is not enough information to help... Could you open the Task Manager to take a look at the memory Jackett is using after searching in "all indexers"?
I have Jackett running in a Linux server with 250 MB of RAM and more than 50 indexers configured. There are not memory issues and you have 16 GB...

**Comment by TomW1605** [comment]
so i put Jacket under as much load as i could (detailed below) and my total ram usage was steady at around 40-50% and jacket was using at most 100,000 K (not sure what unit this is) acording to task manager.

i should mention that i have added 4 GB of ram and also that i am no longer using the catch all indexer but am still having the crashes.

my testing method was to tel both sonarr and lidarr to test all indexers (catch all and individual) and tell radarr to test just the catrch all (no test all button) and also run 2 independant searches directly in Jackett

i hope this info helps and let me know if you need any more and i will try and get back a bit quicker

**Comment by ngosang** [comment]
> jacket was using at most 100,000 K (not sure what unit this is) acording to task manager.

That is less than 100 MB of memory.

Are you using Docker? My guess is you are limiting the maximum memory that Jackett can use and your limit is around 100 MB (Jackett needs at least 250 MB to work well). By default we don't limit the maximum memory, but, if you are using Docker, Systemd, etc... they could be limiting the memory.

**Comment by TomW1605** [comment]
i am not using docker. i have jackett installed directly on a windows 7 machine and dont eaven know how to cap the memory usage. jackett is running as a service if that makes a difrance.

**Comment by ngosang** [comment]
I can't provide help for Windows. Maybe @cadatoiva or @junglebus

**Comment by junglebus** [comment]
@TomW1605 Can you try Jackett v0.13 as it had some improvements for Windows. Also, any chance you can try on Windows 10?

**Comment by junglebus** [comment]
@garfield69 @ngosang @cadatoiva 
Any thoughts of changing the default aggregate indexer from 40 secs to 25 seconds and also just using the first say 15 indexers?

**Comment by ngosang** [comment]
> Any thoughts of changing the default aggregate indexer from 40 secs to 25 seconds and also just using the first say 15 indexers?

I'm opposed to both because we are not providing an alternative. I use around 50 in my daily basics because it's really hard to find content in non-English language. The solution has to be something like #7170
I have an automated tool to test around 300 indexers at the same time and the memory consumption is high, but it never crash due to OutOfMemory. Must be something else. Maybe a bug in a C# indexer? I fixed a bug in Mejortorrent recently that was crashing Jackett completely because it was opening +300 requests at once.

@TomW1605 Could you share the list of configured indexers in your installation?

**Comment by TomW1605** [comment]
@junglebus im not exactly sure how to update. i hit cheack for updates and nothing happened, so is there a way to manualy update? as for windows 10 i am working on it at the moment but i dont have much time so it might be a while. it is also worth noting that in an atempt to fix this i have switched away from using the agregate tracker but i am still having the issue.

also please find attached a screen shot of my indexers. please note that the ones that have errors are disabled in sonarr, etc.
![2020-02-22 20 15 51](https://user-images.githubusercontent.com/17092573/75092322-5319e600-55b1-11ea-86b3-8f8343cceb9b.png)

if there is any other info you need let me know. i will keep you informed if somthing comes up.

**Comment by TomW1605** [comment]
one other thing. my plan for switching to windows 10 is a fresh install not an upgrade and my windows 7 install is about 4 years old and quite messed up so there could easaly be somthing there that is causing an issue.

also since first encountering the issue i have upgraded from 16 to 20 GB of ram and that dident help either

**Comment by junglebus** [comment]
@TomW1605 
Just download `Jackett.Installer.Windows.exe` from here: https://github.com/Jackett/Jackett/releases/tag/v0.13.173
And then run the exe to upgrade

@ngosang 
https://support.microsoft.com/en-au/help/2020006/how-to-troubleshoot-out-of-memory-issues-system-outofmemoryexception-i
https://stackoverflow.com/questions/14186256/net-out-of-memory-exception-used-1-3gb-but-have-16gb-installed
Its much more likely to happen on Windows since the Windows version of Jackett is 32 bit. In saying that, there are plenty of Windows users and they aren't getting this error, which makes me suspect something environmental

In regards to changes to the aggregate indexer, my suggestion wasn't directly related to this ticket. I'm regularly seeing users new to torrents wanting to add EVERY public tracker. Why? If more and more people do that its likely sites will try and ban Jackett. For the users with complex aggregate requirements, I think currently we should be suggesting nzbhydra2 which is designed for these scenarios

**Comment by ngosang** [comment]
I'm sorry for walking out of the topic. I know this is not related to the issue.

> Its much more likely to happen on Windows since the Windows version of Jackett is 32 bit.

What about publishing also x64 for Win? What about reducing the binary size? I'm just asking, maybe there are good reasons to not doing it. https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx

> I'm regularly seeing users new to torrents wanting to add EVERY public tracker. Why? If more and more people do that its likely sites will try and ban Jackett.

We are recommending to prefer individual indexers => https://github.com/Jackett/Jackett#aggregate-indexers
The aggregate indexer sends a lot of requests but at different domains. So we are not flooding any site. I'm not worried about Jackett, blocks by User-Agent are unlikely and we can avoid that with spoofing.
As system admin I understand what you are saying, but we are just a tool, the user has full responsibility. If the user does a bad use of the tool he will be banned by the site. I think we should not limit functionality, even if it is to prevent misuse.

**Comment by cadatoiva** [comment]
I agree with @ngosang on this one. An overhaul to our aggregate indexer situation is needed, but I do not think we should change the default behavior on our current /all indexer because it's called exactly that.

**Comment by cadatoiva** [comment]
@TomW1605 are you still having issues with your Jackett installation? Following up on this since we've done a lot of work on improving memory performance recently.

**Comment by TomW1605** [comment]
@cadatoiva yes i am still having this problem

**Comment by cadatoiva** [comment]
@Jackett/maintainers should we look into migrating the Windows build to 64-bit instead of preferring 32-bit? I can't find any particular reasons why this issue is happening, but that would probably help, since I think the other versions are already 64-bit

**Comment by ngosang** [comment]
@cadatoiva Could you move the conversation about win x64 to the internal chat? I will be out for several days.

**Comment by junglebus** [comment]
@TomW1605 what version are you using?

**Comment by TomW1605** [comment]
curently 0.12.1038.0

i am about to update as i forgot to last time (got busy) and will let you know if that changes anything

**Comment by TomW1605** [comment]
ok i have updated to 0.13.506.0. i will let you know if there are any changes

**Comment by TomW1605** [comment]
ok after updating i have not noticed any crashes so hopfuly this issue is resolved.

i will close this issue
