### ISSUE TITLE
[filelist] Can't add filelist (Config)

### ISSUE THREAD

**Issue by alexneamtu** [Jackett/Jackett#6782]
```
01-03 11:39:56 Debug Connection id "0HLSG63IA0HRL" accepted. 
01-03 11:39:56 Debug Connection id "0HLSG63IA0HRL" started. 
01-03 11:39:56 Info Request starting HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/filelist/config application/json 262 
01-03 11:39:56 Debug Wildcard detected, all requests with hosts will be allowed. 
01-03 11:39:56 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/filelist/config 
01-03 11:39:56 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/filelist/config 
01-03 11:39:56 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/filelist/config 
01-03 11:39:56 Debug POST requests are not supported 
01-03 11:39:56 Debug AuthenticationScheme: Cookies was successfully authenticated. 
01-03 11:39:56 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/filelist/config' 
01-03 11:39:57 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/filelist/config' 
01-03 11:39:57 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-03 11:39:57 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-03 11:39:57 Debug Registered model binder providers, in the following order: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider 
01-03 11:39:57 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
01-03 11:39:57 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
01-03 11:39:57 Debug Execution plan of resource filters (in the following order): None 
01-03 11:39:57 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
01-03 11:39:57 Debug Execution plan of exception filters (in the following order): None 
01-03 11:39:57 Debug Execution plan of result filters (in the following order): None 
01-03 11:39:57 Info Authorization was successful. 
01-03 11:39:57 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-03 11:39:57 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-03 11:39:57 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
01-03 11:39:57 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
01-03 11:39:57 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
01-03 11:39:57 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
01-03 11:39:57 Debug Connection id "0HLSG63IA0HRL", Request id "0HLSG63IA0HRL:00000001": started reading request body. 
01-03 11:39:57 Debug Connection id "0HLSG63IA0HRL", Request id "0HLSG63IA0HRL:00000001": done reading request body. 
01-03 11:39:57 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-03 11:39:57 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-03 11:39:57 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
01-03 11:39:57 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-03 11:39:57 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://filelist.ro/takelogin.php) 
01-03 11:39:58 Debug __cfduid=d0b21e92e9e0fb1516e49841aa474069f1578044398; expires=Sun, 02-Feb-20 09:39:58 GMT; path=/; domain=.filelist.ro; HttpOnly; SameSite=Lax; Secure 
01-03 11:39:58 Debug PHPSESSID=5jfb1b89220tprbeb691t6n31e; path=/ 
01-03 11:39:58 Debug WebClient(HttpWebClient2NetCore): Returning OK => Invalid. 
01-03 11:39:58 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 1794.2227ms 
01-03 11:39:58 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-03 11:39:59 Error Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.FileList.<>c__DisplayClass12_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/FileList.cs:line 93
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.FileList.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/FileList.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.FileList.<>c__DisplayClass12_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/FileList.cs:line 93
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.FileList.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/FileList.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

```

**Jackett version**:  0.12.1402.0
**Mono version**: 6.6.0.161

-------------------------------

**Comment by garfield69** [comment]
from what I can tell, something went wrong with your login attempt.
the log shows `Returning OK => Invalid` from the routine at FileList.cs:line 93 which is part of the login test 
https://github.com/Jackett/Jackett/blob/1a8445dc6fb9f164186a553b3d160a977b68b185/src/Jackett.Common/Indexers/FileList.cs#L88-L95

so I would use your browser to login to the site directly and confirm that your account is ok, that you have no outstanding alerts or unread notices or unread emails, and that your ratio is positive.

**Comment by alexneamtu** [comment]
I dis login with those credentials. I will get the source and debug try to see the actual error message and maybe create a pr to show the dump. :)

**Comment by lucianmldvn** [comment]
I have the same problem. It appears that an older version of jackett (0.12.1361.0) is still working with filelist.ro. It might be a bug, since my credentials are correct and work when I login on the site.

**Comment by alexneamtu** [comment]
So downgrading to 0.12.1361 would work?

**Comment by lucianmldvn** [comment]
Probably. I took that information from filelist’s forums.

**Comment by cesargo169** [comment]
I am facing the same issue. Already tried with versions 0.12.1361 and v0.12.1301. The issue still occurs.

**Comment by BTeodor** [comment]
I have the same issue, tried 0.12.1361 and latest version

**Comment by nemukud** [comment]
Same issue. Seems login changed on filelist. A new field "validator" is required. (info from filelist forum)

**Comment by IIIspaceIII** [comment]
@garfield69 I’ve fixed the issue with the pull request #6827

**Comment by lucianmldvn** [comment]
Cool! Has it been released? If so, in what version?

**Comment by IIIspaceIII** [comment]
@lucianmldvn I think the fix will be in the next release.

**Comment by astalush** [comment]
I updated to Version 0.12.1449.0, still not working. I think like IIIspaceIII said it will be in the next update. Hope so.

**Comment by garfield69** [comment]
Jackett 0.12.1470

**Comment by astalush** [comment]
Excellent. It works like a charm. Thank you.
