### ISSUE TITLE
[teamhd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Prosecutor** [Jackett/Jackett#6970]
Hey! Getting this type of error

Jackett version:  0.12.1582.0

Error:

Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 788    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 949    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73

**Comment by Prosecutor** [comment]
It's not a dupe. The Jackett is hosted on the same server from which I'm loggined to the tracker.

https://prnt.sc/qpaukj

**Comment by garfield69** [comment]
is this the first time you are adding the teamhd indexer to Jackett?

**Comment by Prosecutor** [comment]
@garfield69 Yes, exactly.

**Comment by garfield69** [comment]
you opened #5728 previously but did not get a solve...
Are you now able to open a browser on the same jackett machine to copy the cookie with the same ip address as jackett?
@n-ozerov is this indexer working for you?

**Comment by Prosecutor** [comment]
@garfield69 It was solved. That was on my previous Dedi with other account, also that error was just related with captcha. 

I’ve mentioned, that I’m doing it from the same machine where jackett is located.

**Comment by n-ozerov** [comment]
@garfield69

I'm getting same error when trying to login via cookies. I'm pretty much sure that cookies become invalid when user agent changes because every browser update drops session.

Is there a way to set user agent in definition?

**Comment by garfield69** [comment]
easy enough to test.
so shutdown your jackett service and edit the teamhd.yml indexer and add the following
```json
    headers:
      User-Agent: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"]
```
just after the `Search:` key, replacing the useragent keyword and string with whatever one your browser is using when you grab your cookie
startup the service and test.

if it works I can amend the indexer to add a config option so you can update it at the same time you update the cookie.

**Comment by n-ozerov** [comment]
Maybe i'm doing smth wrong, still getting redirect. :(

But i'm pretty sure login depends upon user-agent.

**Comment by garfield69** [comment]
i've a couple indexers that use
https://github.com/Jackett/Jackett/blob/593680f8d3390d43da3e353002575d746e699f21/src/Jackett.Common/Definitions/torrentquest.yml#L44-L46

**Comment by dimqua** [comment]
Any news? I have the same problem.

**Comment by garfield69** [comment]
beyond my skills. open to volunteers who can help.

**Comment by Lonli-Lokli** [comment]
@n-ozerov You should change user-agent within your browser to the same user agent as Jackett use. On details how it can be done you can follow steps 2 & 3 from https://github.com/Jackett/Jackett/issues/6070#issuecomment-545607603

**Comment by Prosecutor** [comment]
@Lonli-Lokli How to do it in Chrome?

I added in teamhd.yml file these lines and still getting an error.

```
headers:
      User-Agent: ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"]
```

**Comment by Lonli-Lokli** [comment]
@Prosecutor You should follow this instructions https://winaero.com/blog/change-user-agent-chrome/ and set custom user agent, same as in teamhd.yml

**Comment by Prosecutor** [comment]
@Lonli-Lokli Still not working for me.

**Comment by janot** [comment]
@Prosecutor works on my side

I'm not sure if exact steps matter, but here they are:
- open teamhd
- **logout**
- change user-agent in dev tools 
- **delete all teamhd cookies and ctrl+f5**
- log in teamhd and get cookie as usual


Looks like 
```
search: headers: User-Agent:
```
doesn't work. I've checked that Jackett's user agent still remains the same.
Probably because of this: #7786

**Comment by Prosecutor** [comment]
@janot Does not works for me. I'm logging TeamHD where jackett is running(same machine), so the User-Agent is exactly the same for both of them, no need to change them.

**Comment by janot** [comment]
@Prosecutor No, Jackett has it's own user-agent which is hardcoded:
https://github.com/Jackett/Jackett/blob/3f01a615108f08e6665c6702590c513e19725ed4/src/Jackett.Common/Utils/BrowserUtil.cs#L9-L11
There's link in my previous comment to the issue exactly about that.

**Comment by Prosecutor** [comment]
@janot Yep, it works.

**Comment by Erythros** [comment]
Ended up facing the same issue. Since it's still open, is there a solution for this?

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing if this is related to the User-Agent it can be fixed with latest changes.

**Comment by waldens** [comment]
Either this issue cannot be solved by (at least only) modifying UA, or I'm not modifying UA in the right way.

I just made [this change](https://github.com/waldens/Jackett/commit/800b3f638e6fe64877e89e7caf41cd36f0610121) to `teamhd.yml`, then tried again and TeamHD still returns the "[Login Failed, got redirected](https://i.imgur.com/ydYZb28.png)" error.

Here is the request header and response after the above changes, which cannot access TeamHD website properly:
https://p.teknik.io/Simple/7YzLV
Here is the request header and response in browser, which can access website properly:
https://p.teknik.io/Simple/mgR8P

Any help pls?

**Comment by garfield69** [comment]
I take it you used the majomparade or yggcookie as an example for your user-agent
However I believe that these have not been set up correctly and should not be working as intended.
Try the following
```yaml
    user-agent: "[{{ .Config.useragent }}]"
```
and see if that makes a difference.

**Comment by garfield69** [comment]
never mind, that does not work either.

**Comment by garfield69** [comment]
Thus far, the only way I can get my teamhd indexer to work (on my Win10 platform) is to use the unaltered teamhd indexer, in combination with my Chrome browser extension https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg
I first set the user-agent switched option to define a chrome user agent and set it to
``Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`
and enable that config.
Then I login via browser to teamhd web site and grab the cookie and the Jackett indexer accepts it and works.
Since I am not a C# dev I have no idea why we cannot override the user-agent from the yaml despite majomparade and yggcookie using this method (which I believe cannot be working either, so go figure).

**Comment by waldens** [comment]
@garfield69 Thanks. I didn't wanna modify UA on browser side at first because mistakenly thought having to keep this modification in browser for daily use, which is a bit dirty. Just realized multiple sessions are allowed, so only need to modify temporarily in browser. Just tried, works good!

**Comment by angelfire76** [comment]
@garfield69 Thanks for the user agent tip. It's working.

**Comment by ClandestineClout** [comment]
@garfield69 Thanks that tip got my cookie accepted by jackett but now searches turn up no results. I've tried multiple different searches for english titles (which are part of the posted titles) that are on the front page but they return no results.

**Comment by ClandestineClout** [comment]
2021-10-20 09:06:23 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
-- | -- | --
2021-10-20 09:06:23 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
2021-10-20 09:06:23 | Info | Authorization was successful.
2021-10-20 09:06:23 | Debug | Execution plan of result filters (in the following order): None
2021-10-20 09:06:23 | Debug | Execution plan of exception filters (in the following order): None
2021-10-20 09:06:23 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2021-10-20 09:06:23 | Debug | Execution plan of resource filters (in the following order): None
2021-10-20 09:06:23 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-10-20 09:06:23 | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole).
2021-10-20 09:06:23 | Info | Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2021-10-20 09:06:23 | Debug | Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2021-10-20 09:06:23 | Debug | Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2021-10-20 09:06:23 | Debug | 1 candidate(s) found for the request path '/api/v2.0/server/logs'
2021-10-20 09:06:23 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-10-20 09:06:23 | Debug | The request path /api/v2.0/server/logs does not match a supported file type
2021-10-20 09:06:23 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1634735069862
2021-10-20 09:06:23 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1634735069862
2021-10-20 09:06:23 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1634735069862
2021-10-20 09:06:23 | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/logs?_=somenumbercode - -
2021-10-20 09:06:23 | Debug | Connection id "someletter&numbercode" started.
2021-10-20 09:06:23 | Debug | Connection id "someletter&numbercode" accepted.
2021-10-20 09:06:11 | Debug | Connection id "someletter&numbercode" stopped.
2021-10-20 09:06:11 | Debug | Connection id "someletter&numbercode" sending FIN because: "The client closed the connection."
2021-10-20 09:06:11 | Debug | Connection id "someletter&numbercode" disconnecting.
2021-10-20 09:06:11 | Debug | Connection id "someletter&numbercode" received FIN.
2021-10-20 09:06:07 | Info | Request finished HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=hiddenapikey&Query=boss%20baby&Tracker%5B%5D=teamhd&_=somenumbercode - - - 200 - application/json;+charset=utf-8 4916.8940ms
2021-10-20 09:06:07 | Debug | Connection id "someletter&numbercode" completed keep alive response.
2021-10-20 09:06:07 | Info | Executed endpoint 'Jackett.Server.Controllers.ResultsController.Results (JackettConsole)'
2021-10-20 09:06:07 | Info | Executed action Jackett.Server.Controllers.ResultsController.Results (JackettConsole) in 4815.4244ms
2021-10-20 09:06:07 | Debug | The response will be compressed with 'br'.
2021-10-20 09:06:07 | Info | Executing JsonResult, writing value of type 'Jackett.Common.Models.DTO.ManualSearchResult'.
2021-10-20 09:06:07 | Info | Manual search in teamhd for boss baby => Found 0 releases
2021-10-20 09:06:06 | Debug | CACHE Status / Total cached results: 0
2021-10-20 09:06:06 | Debug | CACHE PruneCacheByMaxResultsPerIndexer / Indexer: teamhd / Pruned queries: 0
2021-10-20 09:06:06 | Debug | CACHE CacheResults / Indexer: teamhd / Added: 0 releases
2021-10-20 09:06:06 | Debug | WebClient(HttpWebClient2): Returning OK => 5855 bytes <!DOCTYPE html> <html  lang=ru> <head> <meta http-equiv="Content-type" content="text/html;charset=UTF-8" /> <title>boss%baby &lt; Результаты поиска для::TeamHD</title> <meta name="description" content="  boss%baby &lt; Результаты поиска для" /> <meta name="keywords" content="  boss%baby &lt; Результаты поиска для, " /> <meta name="robots" content="noindex,nofollow"> <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /> <link rel="icon" href="/favicon.ico" type="image/x-icon"> <link rel="alternate" type="application/rss+xml" title="TeamHD RSS Feed"  href="getrss.php"  /> <link rel="stylesheet" href="/themes/teamhd_web/all.min.css" > <link rel="stylesheet" href="/themes/teamhd_web/css/bootstrap.min.css" > <link rel="stylesheet" href="/css/style-main.css?v=0.4" > <script type="text/javascript" src="/js/jquery.js"></script> <script type="text/javascript" src="/js/features.js"></script> <script type="text/javascript" src="/js/jquery-migrate-1.4.1.min.js"></script>     <base href="https://teamhd.org" /> </head> <body> <div class="col-12"><div class="row"><div class="header"><div class="container"><a href="/"><div class="brand d-inline-flex"></div></a></div></div></div></div> <div class="col-12"> <ul class="nav justify-content-center row">   <li class="nav-item"><a class="nav-link" href="/" title="Начальная страница сайта"><span>Главная</span></a></li>   <li class="nav-item"><a class="nav-link" href="/browse" title="Список торрентов, доступных для скачивания "><span>Торренты</span></a></li>   <li class="nav-item"><a class="nav-link" href="/forum" title="Форум"><span>Форум</span></a></li>   <li class="nav-item"><a class="nav-link" href="/upload.php" title="Поделись своими запасами со всеми, не будь жадиной !"><span>Загрузить</span></a></li>   <li class="nav-item"><a class="nav-link" href="/topten.php" title="Топ 10"><span>Топ 10</span></a></li>   <li class="nav-item"><a class="nav-link" href="/rules.php" title="Правила сайта"><span>Правила</span></a></li>   <li class="nav-item"><a class="nav-link" href="/faq.php" title="ЧаВо"><span>ЧаВо</span></a></li>   <li class="nav-item"><a class="nav-link" href="/support.php" title="Помощь"><span>Помощь</span></a></li>   <li class="nav-item"><a class="nav-link" href="/staff.php" title="Команда"><span>Команда</span></a></li>   <li class="nav-item d-none d-lg-block">     <form method="get" class="form-inline" action="/browse"><div class="input-group input-group-sm mt-2">       <input type="text" class="form-control search" name="search" aria-label="Поиск" aria-describedby="inputGroup-sizing-sm col-4">       <div class="input-group-append search">       <button class="btn " type="submit" id="button-addon"><i class="fas fa-search"></i></button></div>     </div></form>   </li> </ul> </div> <div class="col-12"><div class="container"> <div class="row"> <div class="col-12"> <div class="row"> <div class="col-8 mb-4"> <a href="/user/id5392"><span style="color:#d21e36" title="1080i">myusername</span></a></b> &nbsp;[<a href="my.php">Настройки</a>]&nbsp;[<a href="bookmarks.php">Закладки</a>] [<a href="/mybonus.php">Мой бонус</a>] [<a href="/friends.php">Мои друзья</a>] [<a href="/mytorrents.php">Мои торренты</a>] [<a href="/logout.php">Выход!</a>] <br/> <font color=#1900D1>Рейтинг:</font> <font color=#000000>1.704</font>&nbsp;&nbsp; <font color=green>Раздал:</font> 697.12 GB&nbsp;&nbsp; <font color=darkred>Скачал:</font> 409.19 GB</font>&nbsp;&nbsp; <font color=darkblue>Бонус:</font> <a href="/mybonus.php" class="online" title="Потратить">15 157</a>&nbsp;&nbsp; <font color=#1900D1>Торренты:</font> <img alt="Раздает" title="Раздает" src="/themes/teamhd_web/images/arrowup.gif">&nbsp;20&nbsp;&nbsp; <img alt="Качает" title="Качает" src="/themes/teamhd_web/images/arrowdown.gif">&nbsp;0</div> <div class="col-4 text-right mb-4">Текущее время: <span id="hour_min"></span>&nbsp;&nbsp; <a href=/message.php><img alt="inbox" title="Нет новых сообщений" src="/pic/pn_inbox.gif"></a> 7 &nbsp;<a href=/message.php?action=viewmailbox&box=-1><img alt=Отправленые title=Отправленые src=/pic/pn_sentbox.gif></a> 2&nbsp;<a href=/friends.php><img alt=Друзья title=Друзья src=/pic/buddylist.gif></a>&nbsp;<a href=/getrss.php><img alt=RSS title=RSS src=/pic/rss.gif></a></div> </div> </div>   <div class="col-2"><div class="row"><script language="javascript" type="text/javascript" src="/js/blocks.js"></script><html> <head> <title>PHP Error</title>  	    		   <style>P,BODY{ font-family:arial,sans-serif; font-size:11px; }</style> </head> <body>  	    		   <blockquote> <h1>PHP Error</h1><b>Случилась ошибка при выполнение PHP скрипта.</b><br /> 	    		   Попробуйте перезагрузить страницу <a href="javascript:window.location=window.location;">нажав здесь</a>. 	    		   <br /><br /><b>Обработка ошибки</b><br /> 	    		   <form name='php'><textarea rows="15" cols="60">  Дата: Wed, 20 Oct 2021 16:06:13 +0300  Номер ошибки: 2  Ошибка: in_array() expects parameter 2 to be array, boolean given  IP Адресс: 127.0.0.1  в файле /home/teamhd.org/www/include/blocks.php линия 49  URL:/browse?search=boss%25baby&amp;incldead=1&amp;free=0&amp;year=  Имя пользователя: MyUsername[5392]</textarea></form><br>Извиняемся за причиненные неудобства</blockquote></body></html>
2021-10-20 09:06:06 | Debug | cross-site-cookie=https://teamhd.org ;SameSite=None; Secure
2021-10-20 09:06:02 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://teamhd.org/browse?search=boss%25baby&incldead=1&free=0&year=)
2021-10-20 09:06:02 | Debug | CACHE Status / Total cached results: 0
2021-10-20 09:06:02 | Debug | CACHE PruneCacheByTtl / Pruned queries: 0
2021-10-20 09:06:02 | Debug | Done attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2021-10-20 09:06:02 | Debug | Attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ...
2021-10-20 09:06:02 | Debug | Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2021-10-20 09:06:02 | Debug | Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2021-10-20 09:06:02 | Debug | Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]'.
2021-10-20 09:06:02 | Debug | Done attempting to bind model of type 'System.String' using the name 'Tracker[0]'.
2021-10-20 09:06:02 | Debug | Could not find a value in the request with name 'Tracker[0]' of type 'System.String'.
2021-10-20 09:06:02 | Debug | Attempting to bind model of type 'System.String' using the name 'Tracker[0]' in request data ...
2021-10-20 09:06:02 | Debug | Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, Tracker[0]=value1&Tracker[1]=value2, Tracker.index=zero&Tracker.index=one&Tracker[zero]=value1&Tracker[one]=value2
2021-10-20 09:06:02 | Debug | Could not bind to collection using a format like Tracker=value1&Tracker=value2
2021-10-20 09:06:02 | Debug | Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]' using the name 'Tracker' in request data ...
2021-10-20 09:06:02 | Debug | Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
2021-10-20 09:06:02 | Debug | Could not find a value in the request with name 'Category' for binding property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
2021-10-20 09:06:02 | Debug | Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]' using the name 'Category' in request data ...
2021-10-20 09:06:02 | Debug | Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String'.
2021-10-20 09:06:02 | Debug | Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String' using the name 'Query' in request data ...
2021-10-20 09:06:02 | Debug | Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' using the name '' in request data ...
2021-10-20 09:06:02 | Debug | Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ...
2021-10-20 09:06:02 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole)
2021-10-20 09:06:02 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole)
2021-10-20 09:06:02 | Debug | Execution plan of result filters (in the following order): None
2021-10-20 09:06:02 | Debug | Execution plan of exception filters (in the following order): None
2021-10-20 09:06:02 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery
2021-10-20 09:06:02 | Debug | Execution plan of resource filters (in the following order): None
2021-10-20 09:06:02 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-10-20 09:06:02 | Info | Route matched with {action = "Results", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Results(Jackett.Common.Models.DTO.ApiSearch) on controller Jackett.Server.Controllers.ResultsController (JackettConsole).
2021-10-20 09:06:02 | Info | Executing endpoint 'Jackett.Server.Controllers.ResultsController.Results (JackettConsole)'
2021-10-20 09:06:02 | Debug | Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Results (JackettConsole)'
2021-10-20 09:06:02 | Debug | Endpoint 'Jackett.Server.Controllers.ResultsController.Results (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId}/results' is valid for the request path '/api/v2.0/indexers/all/results'
2021-10-20 09:06:02 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/all/results'
2021-10-20 09:06:02 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-10-20 09:06:02 | Debug | The request path /api/v2.0/indexers/all/results does not match a supported file type
2021-10-20 09:06:02 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=myapikey&Query=boss%20baby&Tracker%5B%5D=teamhd&_=somenumbercode
2021-10-20 09:06:02 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=myapikey&Query=boss%20baby&Tracker%5B%5D=teamhd&_=somenumbercode
2021-10-20 09:06:02 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=myapikey&Query=boss%20baby&Tracker%5B%5D=teamhd&_=somenumbercode
2021-10-20 09:06:02 | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=myapikey&Query=boss%20baby&Tracker%5B%5D=teamhd&_=somenumbercode - -
2021-10-20 09:06:02 | Debug | Connection id "someletter&numbercode" started.
2021-10-20 09:06:02 | Debug | Connection id "someletter&numbercode" accepted.

**Comment by ilike2burnthing** [comment]
@garfield69 can you test if the same changes as from https://github.com/Jackett/Jackett/commit/257327da4a321a06fa2b208993c9b8b146b57e6b resolve this?

**Comment by garfield69** [comment]
>can you test if the same changes as from 257327d resolve this?

Partial success.

To recap, previously, using the indexer config panel to save only the cookie would not work, as a `Login failed, got redirected` error would prevent the config panel doing a save.

Now with the indexer config user-agent header loaded to match my browser session, I can save the config and browse with the indexer for torrents.

However, when I try to download one of the torrents, it fails, with a `invalid passkey` error.
So for now, https://github.com/Jackett/Jackett/issues/6970#issuecomment-919649309 still remains the only way to get a fully working indexer for me. :-(

**Comment by garfield69** [comment]
v0.19.162
