### ISSUE TITLE
[Scenetime] Unable to add indexer - request failed

### ISSUE THREAD

**Issue by jpaige5408** [Jackett/Jackett#8716]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid 6.8.3, Docker https://hub.docker.com/r/binhex/arch-jackett

**Jackett Version**: Version 0.16.438.0

**Are you using a proxy or VPN?**: tried with and without proxy, fails either way

### Description

trying to add and configure scenetime indexer results in the following error message in the UI: "request to jackett server failed". Not sure if this is related to similar cloudfare issue or not. don't seem to be having any other issues adding indexers. can provide full / more log info if needed.

### Logged Error Messages

```CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.SceneTime.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 107
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70```

**Comment by nunoguerreirorosa** [comment]
Same issue to me !

**Comment by garfield69** [comment]
The cloudflareSolverRe library was updated for the new challenges beginning with Jackett 0.16.463
The current latest Jackett version is 0.16.496
Since you are on Docker Jackett 0.16.438 I recommend you pull the latest docker image to get updated to 0.16.496 and that should help you access scenetime.

**Comment by nunoguerreirorosa** [comment]
I have the latest docker image and I am still having the same problem.

**Comment by garfield69** [comment]
@nunoguerreirorosa  please access your jackett dashboard and scroll to the bottom and report the Jackett version.

**Comment by jpaige5408** [comment]
docker maintainer must not be on the latest version then. i forced update before posting. thanks

**Comment by ilike2burnthing** [comment]
Docker is currently on v0.16.496-ls65, running it here.

Are you using [linuxserver/jackett](https://hub.docker.com/r/linuxserver/jackett) or another image?

**Comment by nunoguerreirorosa** [comment]
In my case was my DNS server which was not allowing local  recursive requests on the docker bridge network. That was my mistake.

**Comment by normanu** [comment]
For me it is still not working on version 0.16.554.0

`
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SceneTime.<>c__DisplayClass12_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 163
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 168
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
`

**Comment by garfield69** [comment]
@normanu  most likely your issue is that the cookie you provided to the indexer was not accepted by scenetime.
try following https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by normanu** [comment]
There is no indexer cookie box?
Just link, username and password.

Op do 28 mei 2020 21:14 schreef garfield69 <notifications@github.com>:

**Comment by garfield69** [comment]
Hmm. The scenetime indexer works for me, but I'm seeing the captcha challenge
![image](https://user-images.githubusercontent.com/6933240/83186711-10a01080-a181-11ea-8418-c08d45ac01ae.png)
which uses a different part of the indexer code to login.

In that case we are going to need to see the full **enhanced** log to see the html and debug prior to the last error msg you posted. Hopefully this may shed light into the issue.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by jpaige5408** [comment]
eh, still not working for me either. currently on binhex's container, version 0.16.548.0. no cookie box - just link, username and password. 

i've attached an enhanced log, i think anonymized, but if not lemme know and i'll fix it.

[log.txt](https://github.com/Jackett/Jackett/files/4704965/log.txt)

**Comment by garfield69** [comment]
@jpaige5408  the log you provided has only activity for IPTorrents.
This ticket is for Scenetime.

**Comment by jpaige5408** [comment]
weird, not sure what happened there, maybe didn't give time for the log file to refresh before i pulled it or something. i updated my post, log looks more like it.

**Comment by garfield69** [comment]
@ngosang what do you make of the OP's log showing cloudflare's anti-DDoS failing with service unavailable,  is the user's IP blacklisted and blocked?
@jpaige5408  can you confirm that using the same machine that is running Jackett, you can use a browser to login to the web site?

**Comment by normanu** [comment]
I can confirm same machine can visit the site.


Op za 30 mei 2020 05:03 schreef garfield69 <notifications@github.com>:

**Comment by ngosang** [comment]
Cloudflare resolver is working well.
In this tracker we are using the cookie method, so the resolver it's not necessary. If you are seeing Cloudflare error:
1. Cookie is copied wrong.
2. The IP from your machine and Jackett is different (in this case you should install a proxy or vpn in the Jackett machine and configure your browser to use that)
3. Jackett IP is banned (I think this is unlikely)

**Comment by garfield69** [comment]
@jpaige5408  can you show us a screenprint of your scenetime config that is showing the username/password instead of the cookie box?
also, scroll to the bottom of your jackett dashboard and confirm your jackett version. Thanks.

**Comment by garfield69** [comment]
Also, access your jackett dashboard and use the trashbin button to remove your active scenetime config then access the add-a-indexer page and add a fresh one.
Getting the cookie box in the config now?

**Comment by jpaige5408** [comment]
@garfield69 i have yet to be able to add a successful scenetime config, it fails each time. here's what i'm seeing when i try to add:
![2020-05-30 12 44 57 pm](https://user-images.githubusercontent.com/55520028/83335719-48d44b80-a274-11ea-99f0-9d4306a05ad8.png)

results in this:
![2020-05-30 12 45 48 pm](https://user-images.githubusercontent.com/55520028/83337981-71b10c80-a285-11ea-8d07-dee06c26e891.png)

Currently on 0.16.548.0
![2020-05-30 12 46 10 pm](https://user-images.githubusercontent.com/55520028/83337996-855c7300-a285-11ea-8794-ba73c1cb8e78.png)

**Comment by jpaige5408** [comment]
interesting discovery... when i disable proxy, i see this:
![IMG_1025](https://user-images.githubusercontent.com/55520028/83338089-57c3f980-a286-11ea-9eca-802786ce075c.JPG)

however, i tried disabling proxy before i ever opened a ticket here, per my description in the op. this is new.

**Comment by garfield69** [comment]
@ngosang  I don't think the indexer is hard-coded to use the cookie method, rather the cookie method it is invoked only when the cloudflare signature is detected. And it would appear that for users whose IP or what ever does not trigger a cloudflare challenge, they get presented with a regular login form, and it would appear that the scenetime regular login code does not work.

**Comment by jpaige5408** [comment]
So, a workaround for now it seems: disable proxy and i have no problem successfully adding scenetime config. then re-enable proxy, test scenetime config and it passes successfully.

**Comment by garfield69** [comment]
good to know.

**Comment by ngosang** [comment]
@jpaige5408 I committed a fix for user/pass login but I can't test it because I always get the captcha. Could you test the next release and report the feedback?

**Comment by jpaige5408** [comment]
now on version 0.16.589.0, there appears to be no change. with proxy active, i'm just prompted with username and password, have no option to add cookies for scenetime. with proxy disabled, i get the cookie prompt. workaround i mentioned earlier is still working fine

**Comment by garfield69** [comment]
@jpaige5408 you tested too early ;-) Please try Jackett 0.16.598

**Comment by saitoh183** [comment]
Still getting this problem with latest Version 0.16.899.0
```
2020-07-26 15:17:35 | Error | {0} CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447    at Jackett.Common.Indexers.SceneTime.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 107    at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```
After removal, refresh of my page and trying to add i get error

**Comment by garfield69** [comment]
@saitoh183  your IP is suspected by cloudflare as being part of a DDoS attack.
Jackett has no way to solve the current version of the cloudflare anti-DDoS challenge.
an experimental solution is being tried with #9028 but a release will not be available for quite some time to come yet.
I can access scenetime with my jackett indexer, so this suggests that the cloudflare challenge is not global but regional.
so you may want to try using a VPN to allocate an IP from a different region of the world and this may prevent your jackett indexer from getting the challenge during login to scenetime.

**Comment by saitoh183** [comment]
@garfield69 but wont putting a vpn affect my other apps running on the machine(ie: Plex)? Jacket is running on a SoyouStart server. Also why is scenetime the only provider affected?

**Comment by garfield69** [comment]
>Also why is scenetime the only provider affected?

because they were the ones under attack.
